#!/bin/bash
echo "================================================================"
echo "CURALIVE SESSION CONTEXT — $(date '+%Y-%m-%d %H:%M')"
echo "================================================================"
echo ""
echo "=== IDENTITY ==="
echo "I am the founder of CuraLive. You are Chief Architect."
echo "Section 2 rules apply. No code until I confirm."
echo ""
echo "=== LAST 5 COMMITS ==="
git log --oneline -5
echo ""
echo "=== LAST SESSION (source of truth) ==="
awk '/^## SESSION:/{block=""} {block=block"\n"$0} END{print block}' SESSION_LOG.md
echo ""
echo "=== LOCKED FILES — DO NOT TOUCH ==="
echo "  server/recallWebhook.ts"
echo "  server/services/SessionClosePipeline.ts"
echo "  server/services/SegmentOrchestrator.ts"
echo "  server/services/DeterministicGovernanceGateway.ts"
echo "  drizzle/schema.ts"
echo "  server/_core/index.ts"
echo ""
echo "=== RULES ==="
echo "  R1: No autonomous commits | R2: One task, one file"
echo "  R3: Confirm before work | R4: Phase gate enforced"
echo "  R5: DB in Render Shell only | R6: Locked files untouched"
echo "  R7: No schema changes without approval | R8: Close session properly"
echo ""
echo "=== TECH STACK ==="
echo "  Node/TS + PostgreSQL + tRPC/Drizzle + Recall.ai + Ably + React"
echo "  Render: curalive-node.onrender.com + curalive-platform-1.onrender.com"
echo ""
echo "=== CLAUDE: CONFIRM BEFORE ANY WORK ==="
echo "  1. Current phase and gate condition status"
echo "  2. Last known good commit"
echo "  3. Today's single objective"
echo "  4. Section 2 rules read and understood"
echo "================================================================"
