CREATE TABLE `webcast_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`title` varchar(300) NOT NULL,
	`description` text,
	`event_type` enum('webinar','webcast','virtual_event','hybrid_event','on_demand','simulive','audio_conference','capital_markets') NOT NULL DEFAULT 'webinar',
	`industry_vertical` enum('financial_services','corporate_communications','healthcare','technology','professional_services','government','education','media_entertainment','general') NOT NULL DEFAULT 'general',
	`webcast_status` enum('draft','scheduled','live','ended','on_demand','cancelled') NOT NULL DEFAULT 'draft',
	`start_time` bigint,
	`end_time` bigint,
	`timezone` varchar(64) DEFAULT 'UTC',
	`max_attendees` int DEFAULT 1000,
	`registration_count` int DEFAULT 0,
	`peak_attendees` int DEFAULT 0,
	`stream_url` varchar(500),
	`rtmp_key` varchar(256),
	`recording_url` varchar(500),
	`registration_enabled` boolean DEFAULT true,
	`chat_enabled` boolean DEFAULT true,
	`qa_enabled` boolean DEFAULT true,
	`polls_enabled` boolean DEFAULT true,
	`recording_enabled` boolean DEFAULT true,
	`logo_url` varchar(500),
	`primary_color` varchar(20) DEFAULT '#3b82f6',
	`host_name` varchar(200),
	`host_organization` varchar(200),
	`tags` varchar(500),
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `webcast_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `webcast_events_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `webcast_polls` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int NOT NULL,
	`question` varchar(500) NOT NULL,
	`options` text NOT NULL,
	`results` text,
	`poll_status` enum('draft','live','closed') NOT NULL DEFAULT 'draft',
	`allow_multiple` boolean DEFAULT false,
	`show_results_to_attendees` boolean DEFAULT true,
	`total_votes` int DEFAULT 0,
	`created_at` bigint NOT NULL,
	`closed_at` bigint,
	CONSTRAINT `webcast_polls_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webcast_qa` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int NOT NULL,
	`attendee_name` varchar(200) NOT NULL,
	`attendee_email` varchar(255),
	`attendee_company` varchar(200),
	`question` text NOT NULL,
	`qa_status` enum('pending','approved','answered','dismissed','flagged') NOT NULL DEFAULT 'pending',
	`upvotes` int DEFAULT 0,
	`answer` text,
	`answered_by` varchar(200),
	`answered_at` bigint,
	`category` varchar(100),
	`is_anonymous` boolean DEFAULT false,
	`created_at` bigint NOT NULL,
	CONSTRAINT `webcast_qa_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webcast_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int NOT NULL,
	`first_name` varchar(100) NOT NULL,
	`last_name` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`company` varchar(200),
	`job_title` varchar(200),
	`phone` varchar(50),
	`country` varchar(100),
	`custom_fields` text,
	`attended` boolean DEFAULT false,
	`joined_at` bigint,
	`left_at` bigint,
	`watch_time_seconds` int DEFAULT 0,
	`engagement_score` int DEFAULT 0,
	`registration_source` varchar(100) DEFAULT 'direct',
	`utm_source` varchar(100),
	`registered_at` bigint NOT NULL,
	CONSTRAINT `webcast_registrations_id` PRIMARY KEY(`id`)
);
