CREATE TABLE `recall_bots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int,
	`meeting_id` int,
	`recall_bot_id` varchar(100) NOT NULL,
	`meeting_url` text NOT NULL,
	`bot_name` varchar(200) DEFAULT 'Chorus.AI',
	`status` varchar(50) NOT NULL DEFAULT 'created',
	`ably_channel` varchar(200),
	`transcript_json` longtext,
	`summary` text,
	`recording_url` text,
	`error_message` text,
	`started_at` bigint NOT NULL,
	`joined_at` bigint,
	`left_at` bigint,
	`created_at` bigint NOT NULL,
	CONSTRAINT `recall_bots_id` PRIMARY KEY(`id`),
	CONSTRAINT `recall_bots_recall_bot_id_unique` UNIQUE(`recall_bot_id`)
);
