CREATE TABLE `mux_streams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int,
	`meeting_id` int,
	`mux_stream_id` varchar(100) NOT NULL,
	`mux_playback_id` varchar(100),
	`stream_key` varchar(200) NOT NULL,
	`rtmp_url` varchar(300) DEFAULT 'rtmps://global-live.mux.com:443/app',
	`status` varchar(50) NOT NULL DEFAULT 'idle',
	`label` varchar(200),
	`is_public` boolean DEFAULT true,
	`recording_enabled` boolean DEFAULT true,
	`mux_asset_id` varchar(100),
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	`started_at` bigint,
	`ended_at` bigint,
	CONSTRAINT `mux_streams_id` PRIMARY KEY(`id`),
	CONSTRAINT `mux_streams_mux_stream_id_unique` UNIQUE(`mux_stream_id`)
);
