CREATE TABLE `event_customisation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(128) NOT NULL,
	`client_name` varchar(200) NOT NULL DEFAULT 'PulseLive',
	`logo_url` varchar(500),
	`primary_color` varchar(20) DEFAULT '#c8a96e',
	`accent_color` varchar(20) DEFAULT '#10b981',
	`font_family` varchar(100) DEFAULT 'Space Grotesk',
	`show_powered_by` boolean DEFAULT true,
	`reg_page_title` varchar(300),
	`reg_page_subtitle` varchar(500),
	`reg_host_name` varchar(200),
	`reg_host_title` varchar(200),
	`reg_host_org` varchar(200),
	`reg_event_date` varchar(100),
	`reg_event_time` varchar(100),
	`reg_event_timezone` varchar(64) DEFAULT 'SAST',
	`reg_description` text,
	`reg_features` text,
	`reg_agenda` text,
	`reg_speakers` text,
	`reg_industry_vertical` varchar(64) DEFAULT 'general',
	`reg_max_attendees` int DEFAULT 1000,
	`reg_consent_text` text,
	`reg_support_email` varchar(320),
	`reg_field_company` boolean DEFAULT true,
	`reg_field_job_title` boolean DEFAULT true,
	`reg_field_phone` boolean DEFAULT false,
	`reg_field_country` boolean DEFAULT false,
	`reg_field_language` boolean DEFAULT true,
	`reg_field_dial_in` boolean DEFAULT true,
	`book_headline` varchar(300),
	`book_subheadline` varchar(500),
	`book_features` text,
	`book_service_options` text,
	`book_reply_email` varchar(320),
	`book_button_label` varchar(100) DEFAULT 'Submit Booking Request',
	`email_sender_name` varchar(200) DEFAULT 'PulseLive',
	`email_sender_address` varchar(320),
	`email_header_color` varchar(20) DEFAULT '#0f172a',
	`email_button_color` varchar(20) DEFAULT '#3b82f6',
	`email_button_label` varchar(100) DEFAULT 'Join Event',
	`email_footer_text` varchar(500),
	`custom_slug` varchar(128),
	`short_link_enabled` boolean DEFAULT false,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `event_customisation_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_customisation_event_id_unique` UNIQUE(`event_id`)
);
--> statement-breakpoint
ALTER TABLE `recall_bots` MODIFY COLUMN `bot_name` varchar(200) DEFAULT 'PulseLive';