CREATE TABLE `billing_clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_name` varchar(255) NOT NULL,
	`registration_number` varchar(128),
	`vat_number` varchar(64),
	`industry` varchar(128),
	`contact_name` varchar(255) NOT NULL,
	`contact_email` varchar(320) NOT NULL,
	`contact_phone` varchar(64),
	`contact_job_title` varchar(255),
	`billing_address` text,
	`billing_city` varchar(128),
	`billing_country` varchar(128) DEFAULT 'South Africa',
	`billing_postal_code` varchar(32),
	`currency` varchar(8) NOT NULL DEFAULT 'ZAR',
	`payment_terms_days` int NOT NULL DEFAULT 30,
	`notes` text,
	`status` enum('active','inactive','prospect') NOT NULL DEFAULT 'prospect',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoice_number` varchar(32) NOT NULL,
	`client_id` int NOT NULL,
	`quote_id` int,
	`title` varchar(255) NOT NULL,
	`subtotal_cents` bigint NOT NULL DEFAULT 0,
	`discount_cents` bigint NOT NULL DEFAULT 0,
	`tax_percent` int NOT NULL DEFAULT 15,
	`tax_cents` bigint NOT NULL DEFAULT 0,
	`total_cents` bigint NOT NULL DEFAULT 0,
	`paid_cents` bigint NOT NULL DEFAULT 0,
	`currency` varchar(8) NOT NULL DEFAULT 'ZAR',
	`status` enum('draft','sent','viewed','unpaid','partial','paid','overdue','cancelled') NOT NULL DEFAULT 'draft',
	`issued_at` timestamp,
	`due_at` timestamp,
	`paid_at` timestamp,
	`access_token` varchar(64),
	`payment_terms` text,
	`internal_notes` text,
	`client_notes` text,
	`bank_details` text,
	`created_by_user_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `billing_invoices_invoice_number_unique` UNIQUE(`invoice_number`),
	CONSTRAINT `billing_invoices_access_token_unique` UNIQUE(`access_token`)
);
--> statement-breakpoint
CREATE TABLE `billing_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quote_id` int,
	`invoice_id` int,
	`description` varchar(512) NOT NULL,
	`category` varchar(128),
	`quantity` int NOT NULL DEFAULT 1,
	`unit_price_cents` bigint NOT NULL,
	`total_cents` bigint NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `billing_line_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoice_id` int NOT NULL,
	`client_id` int NOT NULL,
	`amount_cents` bigint NOT NULL,
	`currency` varchar(8) NOT NULL DEFAULT 'ZAR',
	`payment_method` enum('eft','bank_transfer','cheque','credit_card','other') NOT NULL DEFAULT 'eft',
	`reference` varchar(255),
	`paid_at` timestamp NOT NULL,
	`notes` text,
	`recorded_by_user_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `billing_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quote_number` varchar(32) NOT NULL,
	`client_id` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`subtotal_cents` bigint NOT NULL DEFAULT 0,
	`discount_cents` bigint NOT NULL DEFAULT 0,
	`tax_percent` int NOT NULL DEFAULT 15,
	`total_cents` bigint NOT NULL DEFAULT 0,
	`currency` varchar(8) NOT NULL DEFAULT 'ZAR',
	`status` enum('draft','sent','viewed','accepted','declined','invoiced','expired') NOT NULL DEFAULT 'draft',
	`issued_at` timestamp,
	`expires_at` timestamp,
	`accepted_at` timestamp,
	`access_token` varchar(64),
	`payment_terms` text,
	`internal_notes` text,
	`client_notes` text,
	`created_by_user_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_quotes_id` PRIMARY KEY(`id`),
	CONSTRAINT `billing_quotes_quote_number_unique` UNIQUE(`quote_number`),
	CONSTRAINT `billing_quotes_access_token_unique` UNIQUE(`access_token`)
);
