CREATE TABLE `ai_generated_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int NOT NULL,
	`content_type` enum('event_summary','press_release','follow_up_email','talking_points','qa_analysis','sentiment_report') NOT NULL,
	`title` varchar(255) NOT NULL,
	`content` longtext NOT NULL,
	`edited_content` longtext,
	`status` enum('generated','approved','rejected','sent') NOT NULL DEFAULT 'generated',
	`recipients` json,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`generated_by` int,
	`approved_at` timestamp,
	`approved_by` int,
	`rejected_at` timestamp,
	`rejection_reason` varchar(500),
	`sent_at` timestamp,
	`sent_to` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_generated_content_id` PRIMARY KEY(`id`)
);
