CREATE TABLE `content_engagement_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`content_id` int NOT NULL,
	`recipient_email` varchar(255) NOT NULL,
	`event_type` enum('sent','opened','clicked','responded','bounced','unsubscribed') NOT NULL,
	`event_data` json,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `content_engagement_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `content_performance_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`content_id` int NOT NULL,
	`event_id` int NOT NULL,
	`content_type` varchar(50) NOT NULL,
	`approval_status` enum('approved','rejected','pending') NOT NULL DEFAULT 'pending',
	`approval_time` int,
	`approval_score` decimal(3,2),
	`recipient_count` int DEFAULT 0,
	`sent_count` int DEFAULT 0,
	`open_count` int DEFAULT 0,
	`click_count` int DEFAULT 0,
	`response_count` int DEFAULT 0,
	`open_rate` decimal(3,2) DEFAULT '0',
	`click_through_rate` decimal(3,2) DEFAULT '0',
	`response_rate` decimal(3,2) DEFAULT '0',
	`engagement_score` decimal(3,2) DEFAULT '0',
	`quality_score` decimal(3,2),
	`relevance_score` decimal(3,2),
	`professionalism_score` decimal(3,2),
	`edits_count` int DEFAULT 0,
	`rejection_reason` varchar(500),
	`notes` longtext,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_performance_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `content_type_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`content_type` varchar(50) NOT NULL,
	`total_generated` int DEFAULT 0,
	`total_approved` int DEFAULT 0,
	`total_rejected` int DEFAULT 0,
	`approval_rate` decimal(3,2) DEFAULT '0',
	`avg_approval_time` int,
	`total_sent` int DEFAULT 0,
	`total_opens` int DEFAULT 0,
	`total_clicks` int DEFAULT 0,
	`total_responses` int DEFAULT 0,
	`avg_open_rate` decimal(3,2) DEFAULT '0',
	`avg_click_through_rate` decimal(3,2) DEFAULT '0',
	`avg_response_rate` decimal(3,2) DEFAULT '0',
	`avg_quality_score` decimal(3,2) DEFAULT '0',
	`avg_relevance_score` decimal(3,2) DEFAULT '0',
	`avg_professionalism_score` decimal(3,2) DEFAULT '0',
	`performance_rank` int,
	`trend_direction` enum('improving','stable','declining') DEFAULT 'stable',
	`last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_type_performance_id` PRIMARY KEY(`id`),
	CONSTRAINT `content_type_performance_content_type_unique` UNIQUE(`content_type`)
);
--> statement-breakpoint
CREATE TABLE `event_performance_summary` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` int NOT NULL,
	`content_items_generated` int DEFAULT 0,
	`content_items_approved` int DEFAULT 0,
	`content_items_rejected` int DEFAULT 0,
	`overall_approval_rate` decimal(3,2) DEFAULT '0',
	`avg_time_to_approval` int,
	`total_content_sent` int DEFAULT 0,
	`total_engagements` int DEFAULT 0,
	`avg_engagement_rate` decimal(3,2) DEFAULT '0',
	`best_performing_type` varchar(50),
	`best_performing_score` decimal(3,2) DEFAULT '0',
	`worst_performing_type` varchar(50),
	`worst_performing_score` decimal(3,2) DEFAULT '0',
	`avg_content_quality` decimal(3,2) DEFAULT '0',
	`operator_satisfaction` decimal(2,1),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_performance_summary_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_performance_summary_event_id_unique` UNIQUE(`event_id`)
);
