CREATE TABLE `qa_auto_triage_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`qa_id` int NOT NULL,
	`conference_id` int,
	`classification` enum('approved','duplicate','off_topic','spam','unclear','sensitive') NOT NULL,
	`confidence` int NOT NULL,
	`reason` text,
	`suggested_category` varchar(100),
	`is_duplicate` boolean NOT NULL DEFAULT false,
	`duplicate_of` int,
	`is_sensitive` boolean NOT NULL DEFAULT false,
	`sensitivity_flags` json,
	`triage_score` int NOT NULL,
	`triage_model` varchar(100) NOT NULL DEFAULT 'gpt-4',
	`triage_version` varchar(50) NOT NULL DEFAULT '1.0',
	`triage_timestamp` bigint NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `qa_auto_triage_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `speaking_pace_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`conference_id` int NOT NULL,
	`participant_id` int,
	`speaker_name` varchar(255) NOT NULL,
	`speaker_role` enum('moderator','participant','presenter') NOT NULL DEFAULT 'participant',
	`wpm` int NOT NULL,
	`pace_label` enum('too_slow','slow','normal','fast','too_fast') NOT NULL,
	`pace_score` int NOT NULL,
	`average_pause_ms` int NOT NULL,
	`pause_count` int NOT NULL,
	`pause_score` int NOT NULL,
	`filler_word_count` int NOT NULL,
	`filler_words` json,
	`filler_score` int NOT NULL,
	`overall_score` int NOT NULL,
	`coaching_tip` text,
	`coaching_level` enum('excellent','good','needs_improvement','critical') NOT NULL,
	`window_start_time` bigint NOT NULL,
	`window_end_time` bigint NOT NULL,
	`duration_ms` int NOT NULL,
	`analysis_model` varchar(100) NOT NULL DEFAULT 'whisper-pace-v1',
	`analysis_version` varchar(50) NOT NULL DEFAULT '1.0',
	`analysis_timestamp` bigint NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `speaking_pace_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `toxicity_filter_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`qa_id` int,
	`transcription_segment_id` bigint,
	`conference_id` int,
	`content_type` enum('qa_question','spoken_segment','chat_message') NOT NULL,
	`content` text NOT NULL,
	`toxicity_score` int NOT NULL,
	`toxicity_label` enum('safe','mild','moderate','severe') NOT NULL,
	`is_flagged` boolean NOT NULL DEFAULT false,
	`is_price_sensitive` boolean NOT NULL DEFAULT false,
	`is_confidential` boolean NOT NULL DEFAULT false,
	`is_legal_risk` boolean NOT NULL DEFAULT false,
	`is_abusive` boolean NOT NULL DEFAULT false,
	`is_spam` boolean NOT NULL DEFAULT false,
	`detected_issues` json,
	`risk_level` enum('safe','low','medium','high','critical') NOT NULL,
	`recommended_action` enum('approve','review','flag_moderator','block','redact') NOT NULL,
	`filter_model` varchar(100) NOT NULL DEFAULT 'perspective-api-v2',
	`filter_version` varchar(50) NOT NULL DEFAULT '1.0',
	`filter_confidence` int NOT NULL,
	`filter_timestamp` bigint NOT NULL,
	`moderator_reviewed` boolean NOT NULL DEFAULT false,
	`moderator_action` enum('approved','rejected','redacted','escalated'),
	`moderator_notes` text,
	`reviewed_by` int,
	`reviewed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `toxicity_filter_results_id` PRIMARY KEY(`id`)
);
