CREATE TABLE `event_brief_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`conference_id` int NOT NULL,
	`event_id` varchar(128),
	`operator_id` int,
	`press_release` text NOT NULL,
	`press_release_title` varchar(255),
	`brief_title` varchar(255) NOT NULL,
	`brief_summary` text NOT NULL,
	`key_messages` json NOT NULL,
	`talking_points` json NOT NULL,
	`anticipated_questions` json NOT NULL,
	`financial_highlights` json,
	`brief_model` varchar(100) NOT NULL DEFAULT 'gpt-4',
	`brief_version` varchar(50) NOT NULL DEFAULT '1.0',
	`generation_confidence` int NOT NULL,
	`generation_timestamp` bigint NOT NULL,
	`operator_approved` boolean NOT NULL DEFAULT false,
	`operator_notes` text,
	`approved_at` timestamp,
	`used_in_event` boolean NOT NULL DEFAULT false,
	`used_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_brief_results_id` PRIMARY KEY(`id`)
);
