CREATE TABLE `followup_email_draft_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(128) NOT NULL,
	`conference_id` int NOT NULL,
	`contact_id` int NOT NULL,
	`contact_name` varchar(255) NOT NULL,
	`contact_email` varchar(320) NOT NULL,
	`contact_company` varchar(255),
	`contact_role` varchar(255),
	`email_subject` varchar(255) NOT NULL,
	`email_body` longtext NOT NULL,
	`personalization_level` enum('generic','basic','advanced','premium') NOT NULL DEFAULT 'advanced',
	`sentiment_tone` enum('formal','friendly','enthusiastic','neutral') NOT NULL DEFAULT 'friendly',
	`event_highlights` json,
	`call_to_action` varchar(255),
	`variant_id` varchar(64),
	`variant_type` enum('control','variant_a','variant_b') DEFAULT 'control',
	`generation_model` varchar(100) NOT NULL DEFAULT 'gpt-4',
	`generation_confidence` int NOT NULL,
	`operator_approved` boolean NOT NULL DEFAULT false,
	`operator_notes` text,
	`approved_at` timestamp,
	`sent` boolean NOT NULL DEFAULT false,
	`sent_at` timestamp,
	`opened` boolean NOT NULL DEFAULT false,
	`opened_at` timestamp,
	`clicked` boolean NOT NULL DEFAULT false,
	`clicked_at` timestamp,
	`replied` boolean NOT NULL DEFAULT false,
	`replied_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `followup_email_draft_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `press_release_draft_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(128) NOT NULL,
	`conference_id` int NOT NULL,
	`release_title` varchar(255) NOT NULL,
	`release_summary` text NOT NULL,
	`release_body` longtext NOT NULL,
	`key_highlights` json,
	`financial_metrics` json,
	`speaker_quotes` json,
	`sens_compliant` boolean NOT NULL DEFAULT true,
	`rns_compliant` boolean NOT NULL DEFAULT true,
	`compliance_notes` text,
	`generation_model` varchar(100) NOT NULL DEFAULT 'gpt-4',
	`generation_confidence` int NOT NULL,
	`operator_approved` boolean NOT NULL DEFAULT false,
	`operator_notes` text,
	`approved_at` timestamp,
	`published` boolean NOT NULL DEFAULT false,
	`published_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `press_release_draft_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `silence_anomaly_detector_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(128) NOT NULL,
	`conference_id` int NOT NULL,
	`silence_detected` boolean NOT NULL,
	`silence_duration_seconds` int,
	`silence_start_time` bigint,
	`silence_end_time` bigint,
	`anomaly_type` enum('silence','background_noise','echo','distortion','connection_loss') NOT NULL,
	`anomaly_severity` enum('low','medium','high','critical') NOT NULL,
	`anomaly_confidence` int NOT NULL,
	`suggested_actions` json,
	`operator_alerted` boolean NOT NULL DEFAULT false,
	`operator_response` varchar(255),
	`resolved_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `silence_anomaly_detector_results_id` PRIMARY KEY(`id`)
);
