import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Leaf, ChevronLeft, Loader2, Download, TreePine, Zap, Wifi, Users } from "lucide-react";

export default function SustainabilityDashboard() {
  const [, navigate] = useLocation();
  const [eventId, setEventId] = useState("");
  const [duration, setDuration] = useState("1.5");
  const [result, setResult] = useState<any>(null);

  const calcMutation = trpc.webcast.optimizeSustainability.useMutation({
    onSuccess: (data) => {
      setResult(data);
      toast.success(`Sustainability grade: ${data.grade}`, { description: `${data.carbonSavedKg.toFixed(1)}kg CO₂ saved` });
    },
    onError: () => toast.error("Sustainability calculation failed"),
  });

  const gradeColor: Record<string, string> = {
    "A+": "text-emerald-400", A: "text-emerald-400", B: "text-lime-400", C: "text-amber-400", D: "text-red-400",
  };
  const gradeBg: Record<string, string> = {
    "A+": "from-emerald-500 to-green-600", A: "from-emerald-500 to-teal-600", B: "from-lime-500 to-green-500", C: "from-amber-500 to-yellow-500", D: "from-red-500 to-orange-500",
  };

  const handleDownloadCertificate = () => {
    if (!result) return;
    const cert = result.certificate;
    const content = `
CuraLive Green Event Certificate
══════════════════════════════════════

Event: ${cert.eventTitle}
Event ID: ${cert.eventId}
Issued: ${new Date(cert.issuedAt).toLocaleDateString()}

Sustainability Grade: ${cert.grade}

${cert.badgeText}

Carbon Breakdown:
• Travel avoided: ${result.attendeesTravelAvoided} attendees × ~180km = ${result.breakdown.travelSavings.toFixed(1)}kg CO₂ saved
• Server energy: ${result.serverEnergyKwh.toFixed(2)} kWh = ${result.breakdown.serverCost.toFixed(2)}kg CO₂
• Bandwidth: ${result.bandwidthCo2Kg.toFixed(2)}kg CO₂
• Net saving: ${result.carbonSavedKg.toFixed(1)}kg CO₂

Equivalent to ${result.equivalentTreeDays} tree-days of carbon absorption.

Generated by CuraLive Sustainability Engine
`.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `green-event-certificate-${cert.eventId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Certificate downloaded");
  };

  return (
    <div className="min-h-screen bg-[#0a0d1a] text-white">
      <div className="border-b border-slate-800 px-4 py-3 flex items-center gap-3">
        <button onClick={() => navigate("/")} className="p-1.5 rounded-lg hover:bg-slate-800 transition-colors">
          <ChevronLeft className="w-4 h-4 text-slate-400" />
        </button>
        <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center">
          <Leaf className="w-4 h-4 text-white" />
        </div>
        <div>
          <h1 className="text-base font-bold text-white">Sustainability Dashboard</h1>
          <p className="text-xs text-slate-400">Carbon footprint, ESG reporting, and green event certification</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="rounded-2xl bg-slate-900 border border-slate-800 p-6 mb-6">
          <h2 className="text-sm font-semibold text-slate-200 mb-3">Calculate Event Sustainability</h2>
          <div className="flex gap-3">
            <input
              type="text"
              placeholder="Event ID"
              value={eventId}
              onChange={e => setEventId(e.target.value)}
              className="flex-1 bg-slate-800 border border-slate-700 rounded-xl px-4 py-2.5 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/50"
            />
            <input
              type="number"
              placeholder="Hours"
              value={duration}
              onChange={e => setDuration(e.target.value)}
              className="w-24 bg-slate-800 border border-slate-700 rounded-xl px-4 py-2.5 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/50"
            />
            <button
              onClick={() => calcMutation.mutate({ eventId, durationHours: parseFloat(duration) || 1.5 })}
              disabled={!eventId.trim() || calcMutation.isPending}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-green-600 text-white text-sm font-medium disabled:opacity-50 hover:opacity-90 transition-opacity"
            >
              {calcMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Leaf className="w-4 h-4" />}
              Calculate
            </button>
          </div>
        </div>

        {result && (
          <div className="space-y-5">
            <div className={`rounded-2xl bg-gradient-to-br ${gradeBg[result.grade] ?? "from-slate-700 to-slate-800"} p-6 text-white`}>
              <div className="flex items-center justify-between mb-4">
                <div>
                  <div className="text-sm opacity-80 mb-1">Sustainability Grade</div>
                  <div className="text-6xl font-black">{result.grade}</div>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold">{result.carbonSavedKg.toFixed(0)}</div>
                  <div className="text-sm opacity-80">kg CO₂ saved</div>
                </div>
              </div>
              <div className="text-sm opacity-90 leading-relaxed">{result.certificate?.badgeText}</div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              {[
                { icon: Users, label: "Attendees Travel Avoided", value: result.attendeesTravelAvoided, unit: "people", color: "text-blue-400" },
                { icon: TreePine, label: "Tree-Day Equivalent", value: result.equivalentTreeDays, unit: "tree-days", color: "text-green-400" },
                { icon: Zap, label: "Server Energy Used", value: result.serverEnergyKwh.toFixed(2), unit: "kWh", color: "text-amber-400" },
                { icon: Wifi, label: "Bandwidth CO₂", value: result.bandwidthCo2Kg.toFixed(3), unit: "kg CO₂", color: "text-purple-400" },
              ].map(({ icon: Icon, label, value, unit, color }) => (
                <div key={label} className="rounded-xl bg-slate-900 border border-slate-800 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Icon className={`w-4 h-4 ${color}`} />
                    <span className="text-xs text-slate-400">{label}</span>
                  </div>
                  <div className={`text-2xl font-bold ${color}`}>{value}</div>
                  <div className="text-xs text-slate-500">{unit}</div>
                </div>
              ))}
            </div>

            <div className="rounded-2xl bg-slate-900 border border-slate-800 p-6">
              <h3 className="text-sm font-semibold text-slate-200 mb-4">Carbon Breakdown</h3>
              <div className="space-y-3">
                {[
                  { label: "Travel saved (vs in-person attendance)", value: `+${result.breakdown.travelSavings.toFixed(1)} kg`, positive: true },
                  { label: "Server energy cost", value: `-${result.breakdown.serverCost.toFixed(2)} kg`, positive: false },
                  { label: "Bandwidth cost", value: `-${result.breakdown.bandwidthCost.toFixed(3)} kg`, positive: false },
                  { label: "Net CO₂ saving", value: `${result.breakdown.netSaving.toFixed(1)} kg`, positive: result.breakdown.netSaving > 0, bold: true },
                ].map(({ label, value, positive, bold }) => (
                  <div key={label} className={`flex justify-between items-center text-sm ${bold ? "font-semibold border-t border-slate-700 pt-3 mt-1" : ""}`}>
                    <span className="text-slate-400">{label}</span>
                    <span className={positive ? "text-emerald-400" : "text-red-400"}>{value}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-2xl bg-slate-900 border border-slate-800 p-6">
              <h3 className="text-sm font-semibold text-slate-200 mb-3 flex items-center gap-2">
                <Leaf className="w-4 h-4 text-emerald-400" /> Green Suggestions
              </h3>
              <ul className="space-y-2">
                {(result.suggestions ?? []).map((s: string, i: number) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-400">
                    <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                    {s}
                  </li>
                ))}
              </ul>
            </div>

            <button
              onClick={handleDownloadCertificate}
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-gradient-to-r from-emerald-500 to-green-600 text-white text-sm font-medium hover:opacity-90 transition-opacity"
            >
              <Download className="w-4 h-4" /> Download ESG Green Event Certificate
            </button>
          </div>
        )}

        {!result && !calcMutation.isPending && (
          <div className="rounded-2xl bg-slate-900 border border-slate-700/50 border-dashed p-12 text-center">
            <Leaf className="w-10 h-10 text-slate-600 mx-auto mb-3" />
            <div className="text-sm text-slate-500">Enter an event ID to calculate carbon savings and generate your ESG certificate</div>
          </div>
        )}
      </div>
    </div>
  );
}
