/**
 * email.ts — Transactional email helper using Resend.
 *
 * Usage:
 *   import { sendEmail } from "./_core/email";
 *   await sendEmail({ to: "ir@client.com", subject: "...", html: "..." });
 *
 * Falls back gracefully (logs warning) when RESEND_API_KEY is not set,
 * so the app continues to work in dev without credentials.
 */
import { Resend } from "resend";
import { ENV } from "./env";

const FROM_ADDRESS = "CuraLive <noreply@curalive.cc>";
const FROM_ADDRESS_FALLBACK = "CuraLive <onboarding@resend.dev>"; // Resend's shared domain for testing

function getResend() {
  if (!ENV.resendApiKey) return null;
  return new Resend(ENV.resendApiKey);
}

export interface SendEmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  replyTo?: string;
}

export async function sendEmail(opts: SendEmailOptions): Promise<{ success: boolean; id?: string; error?: string }> {
  const resend = getResend();

  if (!resend) {
    console.warn("[Email] RESEND_API_KEY not set — email not sent:", opts.subject);
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  // Use the shared Resend test domain if a custom domain hasn't been verified yet
  const from = FROM_ADDRESS_FALLBACK;

  try {
    const { data, error } = await resend.emails.send({
      from,
      to: ENV.isStaging && ENV.stagingSafeEmailRecipient ? [ENV.stagingSafeEmailRecipient] : (Array.isArray(opts.to) ? opts.to : [opts.to]),
      subject: opts.subject,
      html: opts.html,
      replyTo: opts.replyTo,
    });

    if (error) {
      console.error("[Email] Resend error:", error);
      return { success: false, error: error.message };
    }

    console.log("[Email] Sent successfully:", data?.id, "→", opts.subject);
    return { success: true, id: data?.id };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[Email] Unexpected error:", msg);
    return { success: false, error: msg };
  }
}

// ─── Email templates ──────────────────────────────────────────────────────────

export function buildIRSummaryEmail(opts: {
  contactName: string;
  eventTitle: string;
  company: string;
  summary: string;
  date: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${opts.eventTitle} — Post-Event Summary</title>
</head>
<body style="margin:0;padding:0;background:#0a0d14;font-family:'Inter',Arial,sans-serif;color:#e2e8f0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0d14;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1e293b;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1e3a5f,#0f172a);padding:32px 40px;">
              <p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#60a5fa;">CuraLive Intelligence Platform</p>
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#f1f5f9;line-height:1.3;">${opts.eventTitle}</h1>
              <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">${opts.company} · ${opts.date}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#94a3b8;">Dear ${opts.contactName},</p>
              <p style="margin:0 0 24px;font-size:15px;color:#94a3b8;line-height:1.6;">
                Please find below the AI-generated executive summary from today's event.
              </p>
              <div style="background:#0f172a;border-left:3px solid #3b82f6;border-radius:4px;padding:20px 24px;margin:0 0 24px;">
                <p style="margin:0;font-size:14px;color:#cbd5e1;line-height:1.7;white-space:pre-wrap;">${opts.summary}</p>
              </div>
              <p style="margin:0 0 8px;font-size:13px;color:#64748b;line-height:1.6;">
                This summary was generated by CuraLive's intelligence platform. For the full transcript and analytics, 
                please contact your CuraLive account manager.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                CuraLive · Powered by CuraLive Inc. · This email was sent to ${opts.contactName}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

export function buildRegistrationConfirmationEmail(opts: {
  firstName: string;
  lastName: string;
  eventTitle: string;
  company: string;
  eventDate: string;
  dialInNumber?: string;
  accessCode?: string;
  attendUrl?: string;
  icsContent?: string;
  accessPin?: string;
  joinMethod?: "phone" | "teams" | "zoom" | "web";
}): string {
  const joinMethodLabels: Record<string, { label: string; color: string; icon: string; instructions: string }> = {
    phone: { label: "Phone Dial-In", color: "#8b5cf6", icon: "&#128222;", instructions: "Dial the event number and enter your personal PIN when prompted. You will be connected directly to the conference." },
    teams: { label: "Microsoft Teams", color: "#6264a7", icon: "&#128187;", instructions: "A Microsoft Teams meeting link will be sent to you before the event. Click the link at the scheduled time to join." },
    zoom: { label: "Zoom", color: "#2d8cff", icon: "&#127909;", instructions: "A Zoom meeting link will be sent to you before the event. Click the link at the scheduled time to join." },
    web: { label: "Web Browser", color: "#3b82f6", icon: "&#127760;", instructions: "Join directly from your web browser. A link to the CuraLive web attendee room will be sent before the event." },
  };

  const method = opts.joinMethod ? joinMethodLabels[opts.joinMethod] : null;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registration Confirmed — ${opts.eventTitle}</title>
</head>
<body style="margin:0;padding:0;background:#0a0d14;font-family:'Inter',Arial,sans-serif;color:#e2e8f0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0d14;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1e293b;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#14532d,#0f172a);padding:32px 40px;">
              <p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#4ade80;">Registration Confirmed</p>
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#f1f5f9;line-height:1.3;">${opts.eventTitle}</h1>
              <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">${opts.company} · ${opts.eventDate}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#94a3b8;">Dear ${opts.firstName} ${opts.lastName},</p>
              <p style="margin:0 0 24px;font-size:15px;color:#94a3b8;line-height:1.6;">
                Your registration has been confirmed. ${method ? `You have chosen to join via <strong style="color:#f1f5f9;">${method.label}</strong>.` : 'Use the details below to join when the event goes live.'}
              </p>
              ${method ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f172a;border-radius:10px;border:1px solid ${method.color}40;margin:0 0 24px;">
                <tr>
                  <td style="padding:16px 20px;border-bottom:1px solid #1e293b;">
                    <p style="margin:0;font-size:13px;font-weight:700;color:${method.color};">${method.icon}&nbsp; Your Join Method: ${method.label}</p>
                  </td>
                </tr>
                <tr>
                  <td style="padding:16px 20px;">
                    <p style="margin:0;font-size:14px;color:#94a3b8;line-height:1.6;">${method.instructions}</p>
                  </td>
                </tr>
              </table>
              ` : ''}
              ${opts.attendUrl ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;">
                <tr>
                  <td align="center">
                    <a href="${opts.attendUrl}" style="display:inline-block;background:#3b82f6;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 32px;border-radius:8px;">Join Event</a>
                  </td>
                </tr>
                <tr>
                  <td align="center" style="padding-top:8px;">
                    <p style="margin:0;font-size:11px;color:#475569;">Or copy this link: ${opts.attendUrl}</p>
                  </td>
                </tr>
              </table>
              ` : ''}
              ${opts.dialInNumber ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f172a;border-radius:8px;padding:20px;margin:0 0 24px;">
                <tr>
                  <td style="padding:8px 0;">
                    <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#64748b;">Dial-In Number</p>
                    <p style="margin:4px 0 0;font-size:18px;font-weight:700;color:#f1f5f9;font-family:monospace;">${opts.dialInNumber}</p>
                  </td>
                </tr>
                ${opts.accessCode ? `
                <tr>
                  <td style="padding:8px 0;border-top:1px solid #1e293b;">
                    <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#64748b;">Participant Code</p>
                    <p style="margin:4px 0 0;font-size:18px;font-weight:700;color:#f1f5f9;font-family:monospace;">${opts.accessCode}</p>
                  </td>
                </tr>
                ` : ''}
              </table>
              ` : ''}
              ${opts.accessPin ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;border-radius:10px;overflow:hidden;border:2px solid #7c3aed;">
                <tr>
                  <td style="background:linear-gradient(135deg,#4c1d95,#1e1b4b);padding:14px 20px;">
                    <p style="margin:0;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#a78bfa;">&#9670;&nbsp; CuraLive Direct &mdash; Your Personal Dial-In PIN</p>
                  </td>
                </tr>
                <tr>
                  <td style="background:#0f172a;padding:20px;">
                    <p style="margin:0 0 12px;font-size:14px;color:#c4b5fd;line-height:1.6;">As a registered attendee you have been assigned a personal PIN. When you dial in, enter your PIN when prompted and you will be connected directly to the conference &mdash; <strong style="color:#f1f5f9;">no operator assistance required</strong>.</p>
                    <table cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="background:#1e1b4b;border:1px solid #7c3aed;border-radius:8px;padding:14px 28px;">
                          <p style="margin:0;font-size:11px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#a78bfa;">Your PIN</p>
                          <p style="margin:4px 0 0;font-size:36px;font-weight:800;color:#f1f5f9;font-family:monospace;letter-spacing:8px;">${opts.accessPin}</p>
                        </td>
                      </tr>
                    </table>
                    <p style="margin:10px 0 0;font-size:12px;color:#6b7280;">Keep this PIN confidential. It is unique to your registration and grants direct access to the conference.</p>
                  </td>
                </tr>
              </table>
              ` : ''}
              ${opts.icsContent ? `
              <p style="margin:0 0 16px;font-size:13px;color:#64748b;line-height:1.6;">
                A calendar invite (.ics) is attached to this email. Open it to add the event to your calendar.
              </p>
              ` : ''}
              <p style="margin:0;font-size:13px;color:#64748b;line-height:1.6;">
                If you have any questions, please contact your CuraLive account manager.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                CuraLive · Powered by CuraLive Inc.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

// ─── Reminder Email Template ──────────────────────────────────────────────────

export interface ReminderEmailOptions {
  firstName: string;
  lastName: string;
  eventTitle: string;
  eventDate: string;       // Human-readable date string, e.g. "Tuesday, 4 March 2026"
  eventTime: string;       // Human-readable time string, e.g. "14:00 UTC"
  attendUrl: string;       // Personal token-gated join link
  reminderType: "24h" | "1h";
  organizerName?: string;
}

/**
 * Build the HTML body for a pre-event reminder email.
 * reminderType "24h" = 24-hour reminder, "1h" = 1-hour reminder.
 */
export function buildReminderEmail(opts: ReminderEmailOptions): string {
  const timeLabel = opts.reminderType === "24h" ? "24 hours" : "1 hour";
  const urgencyColor = opts.reminderType === "1h" ? "#ef4444" : "#3b82f6";
  const urgencyBg = opts.reminderType === "1h" ? "#fef2f2" : "#eff6ff";
  const urgencyBorder = opts.reminderType === "1h" ? "#fecaca" : "#bfdbfe";

  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1.0" /></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
          <!-- Header -->
          <tr>
            <td style="background:#0f172a;padding:28px 40px;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <span style="font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.5px;">
                      Pulse<span style="color:#3b82f6;">Live</span>
                    </span>
                  </td>
                  <td align="right">
                    <span style="font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:1px;">
                      Event Reminder
                    </span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Urgency Banner -->
          <tr>
            <td style="background:${urgencyBg};border-bottom:1px solid ${urgencyBorder};padding:12px 40px;">
              <p style="margin:0;font-size:13px;font-weight:600;color:${urgencyColor};text-align:center;">
                &#9200; Your event starts in <strong>${timeLabel}</strong>
              </p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:36px 40px;">
              <p style="margin:0 0 8px;font-size:22px;font-weight:700;color:#0f172a;line-height:1.3;">
                ${opts.eventTitle}
              </p>
              <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
                Hi ${opts.firstName}, this is your ${timeLabel} reminder for the upcoming event.
              </p>

              <!-- Event Details Box -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;margin-bottom:28px;">
                <tr>
                  <td style="padding:20px 24px;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="padding-bottom:12px;">
                          <span style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;">Date</span><br/>
                          <span style="font-size:15px;font-weight:600;color:#0f172a;">${opts.eventDate}</span>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <span style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;">Time</span><br/>
                          <span style="font-size:15px;font-weight:600;color:#0f172a;">${opts.eventTime}</span>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- CTA -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
                <tr>
                  <td align="center">
                    <a href="${opts.attendUrl}" style="display:inline-block;background:#3b82f6;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:8px;letter-spacing:0.2px;">
                      Join Event Now &#8594;
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Personal link fallback -->
              <p style="margin:0 0 8px;font-size:12px;color:#94a3b8;text-align:center;">
                Or copy your personal link:
              </p>
              <p style="margin:0 0 28px;font-size:11px;color:#3b82f6;text-align:center;word-break:break-all;font-family:monospace;">
                ${opts.attendUrl}
              </p>

              <p style="margin:0;font-size:13px;color:#64748b;line-height:1.6;">
                This link is unique to you &mdash; please do not share it. If you have any questions, contact your CuraLive account manager.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                CuraLive &middot; Powered by ${opts.organizerName ?? "CuraLive Inc."}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

export function buildMailingListInvitationEmail(opts: {
  firstName: string;
  lastName: string;
  eventTitle: string;
  company: string;
  eventDate: string;
  confirmUrl: string;
  dialInNumber?: string;
  personalMessage?: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>You're Invited — ${opts.eventTitle}</title>
</head>
<body style="margin:0;padding:0;background:#0a0d14;font-family:'Inter',Arial,sans-serif;color:#e2e8f0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0d14;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1e293b;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1e3a5f,#0f172a);padding:32px 40px;">
              <p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#60a5fa;">Event Invitation</p>
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#f1f5f9;line-height:1.3;">${opts.eventTitle}</h1>
              <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">${opts.company} · ${opts.eventDate}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#94a3b8;">Dear ${opts.firstName} ${opts.lastName},</p>
              <p style="margin:0 0 24px;font-size:15px;color:#94a3b8;line-height:1.6;">
                You have been invited to attend the upcoming event. Click the button below to choose how you&rsquo;d like to join and confirm your registration.
              </p>
              ${opts.personalMessage ? `
              <div style="background:#0f172a;border-left:3px solid #3b82f6;border-radius:4px;padding:16px 20px;margin:0 0 24px;">
                <p style="margin:0;font-size:14px;color:#cbd5e1;line-height:1.6;">${opts.personalMessage}</p>
              </div>
              ` : ''}
              <!-- CTA Button -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;">
                <tr>
                  <td align="center">
                    <a href="${opts.confirmUrl}" style="display:inline-block;background:#3b82f6;color:#ffffff;font-size:16px;font-weight:700;text-decoration:none;padding:16px 48px;border-radius:8px;letter-spacing:0.3px;">
                      Click here to Register for the Event
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin:0 0 8px;font-size:12px;color:#64748b;text-align:center;">
                Choose how you&rsquo;d like to join — Phone, Microsoft Teams, Zoom, or Web Browser.
              </p>
              <p style="margin:0 0 24px;font-size:12px;color:#64748b;text-align:center;">
                One click and you're registered — no forms to fill in.
              </p>
              ${opts.dialInNumber ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f172a;border-radius:8px;padding:20px;margin:0 0 24px;">
                <tr>
                  <td>
                    <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#64748b;">Dial-In Number</p>
                    <p style="margin:4px 0 0;font-size:18px;font-weight:700;color:#f1f5f9;font-family:monospace;">${opts.dialInNumber}</p>
                    <p style="margin:8px 0 0;font-size:12px;color:#64748b;">Your personal PIN will be provided after registration.</p>
                  </td>
                </tr>
              </table>
              ` : ''}
              <p style="margin:0;font-size:13px;color:#64748b;line-height:1.6;">
                After registering, you will receive a confirmation email with your join details based on the method you choose.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                CuraLive · Powered by CuraLive Inc.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}
