/**
 * email.ts — Transactional email helper using Resend.
 *
 * Usage:
 *   import { sendEmail } from "./_core/email";
 *   await sendEmail({ to: "ir@client.com", subject: "...", html: "..." });
 *
 * Falls back gracefully (logs warning) when RESEND_API_KEY is not set,
 * so the app continues to work in dev without credentials.
 */
import { Resend } from "resend";
import { ENV } from "./env";

const FROM_ADDRESS = "Chorus.AI <noreply@choruscall.ai>";
const FROM_ADDRESS_FALLBACK = "Chorus.AI <onboarding@resend.dev>"; // Resend's shared domain for testing

function getResend() {
  if (!ENV.resendApiKey) return null;
  return new Resend(ENV.resendApiKey);
}

export interface SendEmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  replyTo?: string;
}

export async function sendEmail(opts: SendEmailOptions): Promise<{ success: boolean; id?: string; error?: string }> {
  const resend = getResend();

  if (!resend) {
    console.warn("[Email] RESEND_API_KEY not set — email not sent:", opts.subject);
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  // Use the shared Resend test domain if a custom domain hasn't been verified yet
  const from = FROM_ADDRESS_FALLBACK;

  try {
    const { data, error } = await resend.emails.send({
      from,
      to: Array.isArray(opts.to) ? opts.to : [opts.to],
      subject: opts.subject,
      html: opts.html,
      replyTo: opts.replyTo,
    });

    if (error) {
      console.error("[Email] Resend error:", error);
      return { success: false, error: error.message };
    }

    console.log("[Email] Sent successfully:", data?.id, "→", opts.subject);
    return { success: true, id: data?.id };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[Email] Unexpected error:", msg);
    return { success: false, error: msg };
  }
}

// ─── Email templates ──────────────────────────────────────────────────────────

export function buildIRSummaryEmail(opts: {
  contactName: string;
  eventTitle: string;
  company: string;
  summary: string;
  date: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${opts.eventTitle} — Post-Event Summary</title>
</head>
<body style="margin:0;padding:0;background:#0a0d14;font-family:'Inter',Arial,sans-serif;color:#e2e8f0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0d14;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1e293b;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1e3a5f,#0f172a);padding:32px 40px;">
              <p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#60a5fa;">Chorus.AI Intelligence Platform</p>
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#f1f5f9;line-height:1.3;">${opts.eventTitle}</h1>
              <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">${opts.company} · ${opts.date}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#94a3b8;">Dear ${opts.contactName},</p>
              <p style="margin:0 0 24px;font-size:15px;color:#94a3b8;line-height:1.6;">
                Please find below the AI-generated executive summary from today's event.
              </p>
              <div style="background:#0f172a;border-left:3px solid #3b82f6;border-radius:4px;padding:20px 24px;margin:0 0 24px;">
                <p style="margin:0;font-size:14px;color:#cbd5e1;line-height:1.7;white-space:pre-wrap;">${opts.summary}</p>
              </div>
              <p style="margin:0 0 8px;font-size:13px;color:#64748b;line-height:1.6;">
                This summary was generated by Chorus.AI's intelligence platform. For the full transcript and analytics, 
                please contact your Chorus Call account manager.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                Chorus.AI · Powered by Chorus Call Inc. · This email was sent to ${opts.contactName}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

export function buildRegistrationConfirmationEmail(opts: {
  firstName: string;
  lastName: string;
  eventTitle: string;
  company: string;
  eventDate: string;
  dialInNumber?: string;
  accessCode?: string;
  attendUrl?: string;
  icsContent?: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registration Confirmed — ${opts.eventTitle}</title>
</head>
<body style="margin:0;padding:0;background:#0a0d14;font-family:'Inter',Arial,sans-serif;color:#e2e8f0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0d14;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1e293b;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#14532d,#0f172a);padding:32px 40px;">
              <p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:#4ade80;">Registration Confirmed</p>
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#f1f5f9;line-height:1.3;">${opts.eventTitle}</h1>
              <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">${opts.company} · ${opts.eventDate}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#94a3b8;">Dear ${opts.firstName} ${opts.lastName},</p>
              <p style="margin:0 0 24px;font-size:15px;color:#94a3b8;line-height:1.6;">
                Your registration has been confirmed. Use the button below to join when the event goes live.
              </p>
              ${opts.attendUrl ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;">
                <tr>
                  <td align="center">
                    <a href="${opts.attendUrl}" style="display:inline-block;background:#3b82f6;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 32px;border-radius:8px;">Join Event</a>
                  </td>
                </tr>
                <tr>
                  <td align="center" style="padding-top:8px;">
                    <p style="margin:0;font-size:11px;color:#475569;">Or copy this link: ${opts.attendUrl}</p>
                  </td>
                </tr>
              </table>
              ` : ''}
              ${opts.dialInNumber ? `
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f172a;border-radius:8px;padding:20px;margin:0 0 24px;">
                <tr>
                  <td style="padding:8px 0;">
                    <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#64748b;">Dial-In Number</p>
                    <p style="margin:4px 0 0;font-size:18px;font-weight:700;color:#f1f5f9;font-family:monospace;">${opts.dialInNumber}</p>
                  </td>
                </tr>
                ${opts.accessCode ? `
                <tr>
                  <td style="padding:8px 0;border-top:1px solid #1e293b;">
                    <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#64748b;">Participant Code</p>
                    <p style="margin:4px 0 0;font-size:18px;font-weight:700;color:#f1f5f9;font-family:monospace;">${opts.accessCode}</p>
                  </td>
                </tr>
                ` : ''}
              </table>
              ` : ''}
              ${opts.icsContent ? `
              <p style="margin:0 0 16px;font-size:13px;color:#64748b;line-height:1.6;">
                A calendar invite (.ics) is attached to this email. Open it to add the event to your calendar.
              </p>
              ` : ''}
              <p style="margin:0;font-size:13px;color:#64748b;line-height:1.6;">
                If you have any questions, please contact your Chorus Call account manager.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#0f172a;padding:20px 40px;border-top:1px solid #1e293b;">
              <p style="margin:0;font-size:12px;color:#475569;text-align:center;">
                Chorus.AI · Powered by Chorus Call Inc.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}
