/**
 * Lazy-loading router index
 * This file uses dynamic imports to avoid eager type inference on all routers
 * which was causing TypeScript compilation to exhaust memory
 */

import { router } from "./_core/trpc";

// Import only essential routers eagerly
import { systemRouter } from "./_core/systemRouter";

// Lazy-load all feature routers to reduce initial type inference
export const createAppRouter = async () => {
  // Dynamically import all routers
  const [
    occModule,
    liveVideoModule,
    roadshowAIModule,
    brandingModule,
    webcastModule,
    recallModule,
    muxModule,
    billingModule,
    aiModule,
    webphoneModule,
    customisationModule,
    trainingModeModule,
    postEventReportModule,
    transcriptionModule,
    pollsModule,
    schedulingModule,
    clientPortalModule,
    complianceModule,
    followupsModule,
    sentimentModule,
    mobileNotificationsModule,
    aiDashboardModule,
    aiFeaturesModule,
    analyticsModule,
    contentTriggersModule,
    eventBriefModule,
    liveRollingSummaryModule,
    transcriptEditorModule,
    aiApplicationsModule,
    socialMediaModule,
    interconnectionAnalyticsModule,
    virtualStudioModule,
    operatorLinksModule,
    agenticEventBrainModule,
    autonomousInterventionModule,
    taggedMetricsModule,
    shadowModeModule,
    archiveUploadModule,
    benchmarksModule,
    marketReactionModule,
    communicationIndexModule,
    investorQuestionsModule,
    intelligenceReportModule,
    callPrepModule,
    intelligenceTerminalModule,
    botModule,
  ] = await Promise.all([
    import("./routers/occ"),
    import("./routers/liveVideo"),
    import("./routers/roadshowAI"),
    import("./routers/branding"),
    import("./routers/webcastRouter"),
    import("./routers/recallRouter"),
    import("./routers/muxRouter"),
    import("./routers/billingRouter"),
    import("./routers/aiRouter"),
    import("./routers/webphoneRouter"),
    import("./routers/customisationRouter"),
    import("./routers/trainingMode"),
    import("./routers/postEventReport"),
    import("./routers/transcription"),
    import("./routers/polls"),
    import("./routers/scheduling"),
    import("./routers/clientPortal"),
    import("./routers/compliance"),
    import("./routers/followups"),
    import("./routers/sentiment"),
    import("./routers/mobileNotifications"),
    import("./routers/aiDashboard"),
    import("./routers/aiFeatures"),
    import("./routers/analytics"),
    import("./routers/contentTriggers"),
    import("./routers/eventBriefRouter"),
    import("./routers/liveRollingSummary"),
    import("./routers/transcriptEditorRouter"),
    import("./routers/aiApplications"),
    import("./routers/socialMedia"),
    import("./routers/interconnectionAnalytics"),
    import("./routers/virtualStudioRouter"),
    import("./routers/operatorLinksRouter"),
    import("./routers/agenticEventBrainRouter"),
    import("./routers/autonomousInterventionRouter"),
    import("./routers/taggedMetricsRouter"),
    import("./routers/shadowModeRouter"),
    import("./routers/archiveUploadRouter"),
    import("./routers/benchmarksRouter"),
    import("./routers/marketReactionRouter"),
    import("./routers/communicationIndexRouter"),
    import("./routers/investorQuestionsRouter"),
    import("./routers/intelligenceReportRouter"),
    import("./routers/callPrepRouter"),
    import("./routers/intelligenceTerminalRouter"),
    import("./routers/bot"),
  ]);

  return router({
    system: systemRouter,
    occ: occModule.occRouter,
    liveVideo: liveVideoModule.liveVideoRouter,
    roadshowAI: roadshowAIModule.roadshowAIRouter,
    branding: brandingModule.brandingRouter,
    webcast: webcastModule.webcastRouter,
    recall: recallModule.recallRouter,
    mux: muxModule.muxRouter,
    billing: billingModule.billingRouter,
    ai: aiModule.aiRouter,
    webphone: webphoneModule.webphoneRouter,
    customisation: customisationModule.customisationRouter,
    trainingMode: trainingModeModule.trainingModeRouter,
    postEventReport: postEventReportModule.postEventReportRouter,
    transcription: transcriptionModule.transcriptionRouter,
    polls: pollsModule.pollsRouter,
    scheduling: schedulingModule.schedulingRouter,
    clientPortal: clientPortalModule.clientPortalRouter,
    compliance: complianceModule.complianceRouter,
    followups: followupsModule.followupsRouter,
    sentiment: sentimentModule.sentimentRouter,
    mobileNotifications: mobileNotificationsModule.mobileNotificationsRouter,
    aiDashboard: aiDashboardModule.aiDashboardRouter,
    aiFeatures: aiFeaturesModule.aiFeaturesRouter,
    analytics: analyticsModule.analyticsRouter,
    contentTriggers: contentTriggersModule.contentTriggersRouter,
    eventBrief: eventBriefModule.eventBriefRouter,
    liveRollingSummary: liveRollingSummaryModule.liveRollingSummaryRouter,
    transcriptEditor: transcriptEditorModule.transcriptEditorRouter,
    aiApplications: aiApplicationsModule.aiApplicationsRouter,
    socialMedia: socialMediaModule.socialMediaRouter,
    interconnectionAnalytics: interconnectionAnalyticsModule.interconnectionAnalyticsRouter,
    virtualStudio: virtualStudioModule.virtualStudioRouter,
    operatorLinks: operatorLinksModule.operatorLinksRouter,
    agenticBrain: agenticEventBrainModule.agenticEventBrainRouter,
    autonomousIntervention: autonomousInterventionModule.autonomousInterventionRouter,
    taggedMetrics: taggedMetricsModule.taggedMetricsRouter,
    shadowMode: shadowModeModule.shadowModeRouter,
    archiveUpload: archiveUploadModule.archiveUploadRouter,
    benchmarks: benchmarksModule.benchmarksRouter,
    marketReaction: marketReactionModule.marketReactionRouter,
    communicationIndex: communicationIndexModule.communicationIndexRouter,
    investorQuestions: investorQuestionsModule.investorQuestionsRouter,
    intelligenceReport: intelligenceReportModule.intelligenceReportRouter,
    callPrep: callPrepModule.callPrepRouter,
    intelligenceTerminal: intelligenceTerminalModule.intelligenceTerminalRouter,
    bot: botModule.botRouter,
  });
};
