import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, BorderStyle, AlignmentType, HeadingLevel, ShadingType,
  PageBreak, Tab, TabStopType, TabStopPosition,
} from "docx";
import * as fs from "fs";

const FONT = "Calibri";
const S = 22;

const h1 = (text: string) => new Paragraph({
  heading: HeadingLevel.HEADING_1,
  children: [new TextRun({ text, bold: true, font: FONT, size: 28 })],
  spacing: { before: 400, after: 200 },
});

const h2 = (text: string) => new Paragraph({
  heading: HeadingLevel.HEADING_2,
  children: [new TextRun({ text, bold: true, font: FONT, size: 24 })],
  spacing: { before: 300, after: 150 },
});

const h3 = (text: string) => new Paragraph({
  heading: HeadingLevel.HEADING_3,
  children: [new TextRun({ text, bold: true, font: FONT, size: S })],
  spacing: { before: 200, after: 100 },
});

const p = (text: string) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: S })],
  spacing: { after: 120, line: 360 },
});

const pBold = (text: string) => new Paragraph({
  children: [new TextRun({ text, bold: true, font: FONT, size: S })],
  spacing: { after: 80 },
});

const pItalic = (text: string) => new Paragraph({
  children: [new TextRun({ text, italics: true, font: FONT, size: S })],
  spacing: { after: 80 },
});

const bullet = (text: string, level = 0) => new Paragraph({
  bullet: { level },
  children: [new TextRun({ text, font: FONT, size: S })],
  spacing: { after: 60, line: 340 },
});

const bulletBold = (label: string, rest: string, level = 0) => new Paragraph({
  bullet: { level },
  children: [
    new TextRun({ text: label, bold: true, font: FONT, size: S }),
    new TextRun({ text: rest, font: FONT, size: S }),
  ],
  spacing: { after: 60, line: 340 },
});

const spacer = (n = 200) => new Paragraph({ children: [], spacing: { after: n } });

const hCell = (text: string, width = 2000) => new TableCell({
  children: [new Paragraph({ children: [new TextRun({ text, bold: true, size: 20, font: FONT, color: "FFFFFF" })] })],
  shading: { type: ShadingType.SOLID, color: "1E3A5F" },
  width: { size: width, type: WidthType.DXA },
});

const tCell = (text: string, width = 2000) => new TableCell({
  children: [new Paragraph({ children: [new TextRun({ text, size: 20, font: FONT })] })],
  width: { size: width, type: WidthType.DXA },
});

const pageBreak = () => new Paragraph({ children: [new PageBreak()] });

const diagramLine = (text: string) => new Paragraph({
  children: [new TextRun({ text, font: "Courier New", size: 18 })],
  spacing: { after: 0, line: 240 },
});

const diagramCaption = (text: string) => new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [new TextRun({ text, bold: true, italics: true, font: FONT, size: 20 })],
  spacing: { before: 100, after: 300 },
});

function diagram(lines: string[], caption: string): Paragraph[] {
  return [
    spacer(100),
    ...lines.map(l => diagramLine(l)),
    diagramCaption(caption),
  ];
}

const doc = new Document({
  styles: {
    default: {
      document: { run: { font: FONT, size: S } },
    },
  },
  sections: [
    // ──────────────── COVER PAGE ────────────────
    {
      properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
      children: [
        spacer(600),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "CONTINUATION-IN-PART (CIP)", bold: true, font: FONT, size: 36, color: "1E3A5F" })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "SUPPLEMENTARY PATENT SPECIFICATION", bold: true, font: FONT, size: 30, color: "1E3A5F" })],
          spacing: { after: 80 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Fourth Submission to CIPC", font: FONT, size: 24, color: "4B5563" })],
          spacing: { after: 400 },
        }),
        spacer(200),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "CuraLive Platform", bold: true, font: FONT, size: 32, color: "1E3A5F" })],
          spacing: { after: 100 },
        }),
        spacer(100),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: "Autonomous IR Assistant Layer — Module 30",
            font: FONT, size: 22, italics: true, color: "374151",
          })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: "Autonomous Self-Expansion Engine for AGI Transition — Module 31",
            font: FONT, size: 22, italics: true, color: "374151",
          })],
          spacing: { after: 80 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: "(Extending Modules 1–28 and Claims 1–43 of the Parent Provisional, CIP Submission 2, and CIP Submission 3)",
            font: FONT, size: 18, color: "6B7280",
          })],
          spacing: { after: 600 },
        }),
        spacer(400),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Applicant and Inventor", bold: true, font: FONT, size: 22, color: "1E3A5F" })],
          spacing: { after: 60 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "David Cameron", font: FONT, size: 22 })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "41 Rooigras Avenue, 73 Tiffani Gardens, Bassonia, 2090, Johannesburg, South Africa", font: FONT, size: 20, color: "6B7280" })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "+27 84 444 6001", font: FONT, size: 20, color: "6B7280" })],
          spacing: { after: 400 },
        }),
        spacer(200),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Prepared: 19 March 2026", font: FONT, size: 20 })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Parent Application: No. 1773575338868 (12 March 2026)", font: FONT, size: 20 })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Filing Authority: Companies and Intellectual Property Commission (CIPC)", font: FONT, size: 20, color: "6B7280" })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Jurisdiction: Republic of South Africa — Companies and Intellectual Property Commission (CIPC)", font: FONT, size: 20, color: "6B7280" })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Production URL: https://curalive-platform.replit.app", font: FONT, size: 18, color: "9CA3AF" })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "GitHub: github.com/davecameron187-sys/curalive-platform", font: FONT, size: 18, color: "9CA3AF" })],
          spacing: { after: 40 },
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Document Classification: Confidential — Patent Filing Support Material", font: FONT, size: 18, color: "9CA3AF" })],
        }),

        pageBreak(),

        // ──────────────── TABLE OF CONTENTS ────────────────
        h1("Table of Contents"),
        spacer(100),
        p("1.  Title of Invention"),
        p("2.  Abstract"),
        p("3.  Cross-Reference to Related Applications"),
        p("4.  Field of the Invention"),
        p("5.  Relationship to Parent and Prior CIP Specifications"),
        p("6.  Background of the Invention"),
        p("7.  Summary of the Invention"),
        p("8.  Complete Module Registry (Modules 1–31)"),
        p("9.  Detailed Description — Module 30: Autonomous IR Assistant Layer"),
        p("10. Detailed Description — Module 31: Self-Expansion Engine for AGI Transition"),
        p("11. Embodiments"),
        p("12. Industrial Applicability"),
        p("13. Alternative Implementations"),
        p("14. New Claims (CIP Submission 4)"),
        p("15. Updated Drawings (FIG 28–34)"),
        p("16. Incorporation by Reference"),
        p("17. Declaration"),

        pageBreak(),

        // ──────────────── 1. TITLE ────────────────
        h1("1. Title of Invention"),
        p("System and Method for Autonomous Intelligence Orchestration, Self-Healing Regulatory Compliance, Multi-Event Integrity Certification, Autonomous Agent Swarm Command, Real-Time Valuation Simulation, Self-Auditing Investor Engagement ROI, Autonomous IR Assistant Layer, and Self-Expansion Engine for AGI Transition for Investor Communication Events"),
        spacer(),

        // ──────────────── 2. ABSTRACT ────────────────
        h1("2. Abstract"),
        p("The invention provides a fully autonomous shadow intelligence platform that silently captures every internal and external corporate communication event across any conferencing platform (Zoom, Microsoft Teams, Google Meet, Webex, telephony bridges, and equivalent systems), proactively executes the full scope of Investor Relations (IR), Environmental Social and Governance (ESG), Annual General Meeting (AGM), crisis communications, and Non-Governmental Organisation (NGO) workflows, and continuously self-expands its capabilities toward advanced autonomous intelligence."),
        p("The system delivers zero-input monthly executive intelligence reports, private AI advisory bots, Clean Disclosure Certificates with blockchain integrity certification, and real-time valuation impact analysis. Two novel modules extend all prior filings: Module 30 (Autonomous IR Assistant Layer) provides proactive, zero-input execution of all corporate communications tasks, and Module 31 (Autonomous Self-Expansion Engine) enables seamless evolution of platform capabilities through autonomous gap detection, shadow-mode testing, and self-integration of new AI tools."),
        p("The platform maintains quantum-resistant blockchain certification for all outputs, ensuring audit-proof integrity across all jurisdictions including JSE, SEC, FCA, EU MAR, and equivalent regulatory frameworks."),
        spacer(),

        // ──────────────── 3. CROSS-REFERENCES ────────────────
        h1("3. Cross-Reference to Related Applications"),
        new Table({
          rows: [
            new TableRow({ children: [hCell("Application ID", 2500), hCell("Filing Date", 2000), hCell("Status", 1500), hCell("Scope", 4000)] }),
            new TableRow({ children: [tCell("1773575338868", 2500), tCell("12 March 2026", 2000), tCell("Filed (Parent Provisional)", 1500), tCell("Modules 1–13, Claims 1–25, FIG 1–12", 4000)] }),
            new TableRow({ children: [tCell("CIP Submission 2", 2500), tCell("16 March 2026", 2000), tCell("Filed", 1500), tCell("Modules 19–27, Claims 26–33, FIG 13–20", 4000)] }),
            new TableRow({ children: [tCell("CIP Submission 3", 2500), tCell("18 March 2026", 2000), tCell("Filed", 1500), tCell("Module 28, Claims 34–43, FIG 21–27", 4000)] }),
            new TableRow({ children: [tCell("This Filing (CIP 4)", 2500), tCell("19 March 2026", 2000), tCell("Pending", 1500), tCell("Modules 30–31, Claims 44–55, FIG 28–34", 4000)] }),
          ],
          width: { size: 10000, type: WidthType.DXA },
        }),
        spacer(),

        // ──────────────── 4. FIELD ────────────────
        h1("4. Field of the Invention"),
        p("The present invention relates to artificial intelligence systems for corporate and non-profit communications. More particularly, the invention relates to:"),
        bullet("Investor relations platforms capable of autonomous, proactive execution of IR, ESG, AGM, and crisis communication workflows without human initiation"),
        bullet("Multi-jurisdiction compliance orchestration systems that automatically adapt outputs to the regulatory requirements of different securities exchanges and financial regulators"),
        bullet("Real-time crisis prediction engines that detect emerging communication risks before they manifest in public markets"),
        bullet("Valuation impact analysis systems that simulate the effect of corporate communications on company fair value, share price, and investor sentiment"),
        bullet("Self-expanding AI architectures that autonomously identify capability gaps, generate and test new AI tools, and integrate them into the platform without human intervention"),
        bullet("Shadow intelligence platforms that silently capture and analyse communications across any conferencing platform without requiring configuration by the end user"),
        spacer(),

        // ──────────────── 5. RELATIONSHIP TO PARENT ────────────────
        h1("5. Relationship to Parent and Prior CIP Specifications"),
        p("This CIP Submission 4 builds upon and extends the following prior filings:"),
        spacer(60),
        pBold("Parent Provisional Specification (Application ID 1773575338868, filed 12 March 2026):"),
        p("Disclosed 13 subsystems (Modules 1–13) with 25 independent claims and 12 figures covering real-time event monitoring, AI communication analysis, cross-platform capture via silent agents, OCC operator integration, anonymised benchmarking, autonomous compliance intervention, self-improving models, predictive intelligence, communication indexes, autonomous event intervention, and autonomous self-evolving platform intelligence."),
        spacer(60),
        pBold("CIP Submission 2 (filed 16 March 2026):"),
        p("Extended the parent with 9 autonomous modules (Modules 19–27) adding 8 new independent claims (Claims 26–33) and 8 new figures (FIG 13–20). Modules 14–18 are operational expansion modules (Conference Dial-Out, enhanced OCC, partner integrations, Intelligence Suite) that are part of the built platform but not separately claimed."),
        spacer(60),
        pBold("CIP Submission 3 (filed 18 March 2026):"),
        p("Added Module 28 (Autonomous AI Self-Evolution Engine with Algorithmic Evidence Scoring), contributing 10 new claims (Claims 34–43) and 7 new figures (FIG 21–27). Module 28 comprises six interconnected algorithms that enable the AI to evaluate, improve, and extend itself without any human input."),
        spacer(60),
        pBold("This CIP Submission 4 (19 March 2026):"),
        p("Adds Module 30 (Autonomous IR Assistant Layer) and Module 31 (Autonomous Self-Expansion Engine for AGI Transition), contributing 12 new claims (Claims 44–55) and 7 new figures (FIG 28–34). These modules close the final gap between autonomous intelligence generation and autonomous proactive action."),
        spacer(),

        // ──────────────── 6. BACKGROUND ────────────────
        h1("6. Background of the Invention (Updated)"),
        h2("6.1 Current State of the Art"),
        p("Investor communication events — including earnings calls, investor briefings, capital markets days, annual general meetings, and analyst presentations — are critical touchpoints between listed companies and the investment community. The quality of these communications directly impacts investor confidence, share price stability, regulatory compliance, and corporate reputation."),
        p("Existing systems in this domain fall into several categories, none of which address the full scope of the problem:"),
        spacer(60),
        pBold("Conference and Webcast Platforms (Zoom, Teams, Webex, Chorus Call):"),
        p("Provide broadcasting and recording functionality. No autonomous intelligence generation, compliance monitoring, or proactive workflow execution. Require manual operation for every event."),
        spacer(60),
        pBold("Conversation Intelligence (Gong, Chorus.ai, Fireflies.ai):"),
        p("Generate fixed report types from recorded conversations. Cannot evaluate the quality of their own outputs. Cannot autonomously propose new analysis types. Operate only on sales conversations, not regulated investor communications. No compliance awareness."),
        spacer(60),
        pBold("IR Workflow Platforms (Q4, Notified, Computershare):"),
        p("Provide event scheduling, investor CRM, and basic analytics. All workflows require manual initiation by IR teams. No AI-powered proactive execution. No silent capture from external platforms."),
        spacer(60),
        pBold("AI/ML Observability (LangSmith, LangFuse, Weights & Biases):"),
        p("Track AI model performance metrics. Require human analysts to act on insights. No autonomous self-expansion, tool proposal, or shadow-mode testing capability."),
        spacer(60),
        pBold("Compliance Monitoring (NICE Actimize, Relativity, Global Relay):"),
        p("Monitor for regulatory violations in financial communications. Operate reactively — flagging violations after they occur. No predictive crisis capability. No integration with IR workflow execution."),
        spacer(),

        h2("6.2 Unsolved Problems"),
        p("No known system — in any domain — combines all of the following capabilities in a single platform:"),
        bullet("Silent, platform-agnostic capture across any conferencing system without end-user configuration"),
        bullet("Proactive, zero-input execution of IR, ESG, AGM, crisis, and NGO communication workflows"),
        bullet("Real-time crisis prediction based on communication signal analysis"),
        bullet("Multi-jurisdiction compliance orchestration that automatically adapts to JSE, SEC, FCA, EU MAR, and other regulatory frameworks"),
        bullet("Valuation impact simulation measuring the effect of communications on fair value"),
        bullet("Autonomous self-expansion where the system identifies its own capability gaps, proposes new tools, tests them in shadow mode, and integrates them without human input"),
        bullet("Blockchain-certified audit trail for all intelligence outputs"),
        spacer(),

        // ──────────────── 7. SUMMARY ────────────────
        h1("7. Summary of the Invention (Updated)"),
        p("With this CIP Submission 4, the platform now comprises 31 interconnected subsystems. This filing introduces two new modules that complete the platform's autonomous capability:"),
        spacer(60),
        pBold("Module 30 — Autonomous IR Assistant Layer"),
        p("A fully autonomous background assistant that silently monitors every internal and external meeting across any platform, proactively executes the full scope of IR, ESG, AGM, crisis communications, and NGO workflows, and delivers strategic support outputs — all with zero operator input after initial calendar integration."),
        spacer(60),
        pBold("Module 31 — Autonomous Self-Expansion Engine for AGI Transition"),
        p("An autonomous self-expansion engine that continuously observes its own performance across all communications, identifies new capability gaps, proposes entirely new AI tools, tests them in shadow mode, and seamlessly integrates them into the platform — without any human input — to ensure the system evolves toward advanced autonomous intelligence as the technology matures."),
        spacer(60),
        p("Together with the 29 previously disclosed modules, the platform provides a complete closed-loop intelligence system: events are captured silently, analysed autonomously, actioned proactively, certified immutably, and the system continuously improves itself."),
        spacer(),

        // ──────────────── 8. MODULE REGISTRY ────────────────
        h1("8. Complete Module Registry"),
        new Table({
          rows: [
            new TableRow({ children: [hCell("Module", 800), hCell("Subsystem Name", 5200), hCell("Source", 4000)] }),
            new TableRow({ children: [tCell("1–13", 800), tCell("Core Intelligence Platform (event monitoring, AI analysis, cross-platform capture, OCC, benchmarking, compliance, self-improving models, predictive intelligence, indexes, intervention, self-evolving platform)", 5200), tCell("Parent Provisional (App ID 1773575338868)", 4000)] }),
            new TableRow({ children: [tCell("14–18", 800), tCell("Operational Expansion (Conference Dial-Out, Enhanced OCC, Partner Integrations, Intelligence Suite)", 5200), tCell("Built platform (not separately claimed)", 4000)] }),
            new TableRow({ children: [tCell("19", 800), tCell("Autonomous Event Campaign Orchestrator", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("20", 800), tCell("Self-Healing Regulatory Oracle", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("21", 800), tCell("Autonomous Investor Relationship Graph Weaver", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("22", 800), tCell("Self-Certifying Multi-Event Integrity Chain", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("23", 800), tCell("Autonomous AI Agent Swarm Commander", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("24", 800), tCell("Autonomous Valuation Impact Oracle", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("25", 800), tCell("Self-Auditing Investor Engagement ROI Engine", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("26", 800), tCell("Autonomous Dual-Purpose Compliance & Capital-Raising Advisor", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("27", 800), tCell("Self-Optimising Global Event Intelligence Network", 5200), tCell("CIP Submission 2", 4000)] }),
            new TableRow({ children: [tCell("28", 800), tCell("Autonomous AI Self-Evolution Engine with Algorithmic Evidence Scoring", 5200), tCell("CIP Submission 3", 4000)] }),
            new TableRow({ children: [tCell("30", 800), tCell("Autonomous IR Assistant Layer", 5200), tCell("This Filing (CIP Submission 4)", 4000)] }),
            new TableRow({ children: [tCell("31", 800), tCell("Autonomous Self-Expansion Engine for AGI Transition", 5200), tCell("This Filing (CIP Submission 4)", 4000)] }),
          ],
          width: { size: 10000, type: WidthType.DXA },
        }),
        p("Note: Module 29 is reserved for future disclosure and is not claimed in any current filing."),
        spacer(),

        pageBreak(),

        // ──────────────── 9. MODULE 30 DETAILED ────────────────
        h1("9. Detailed Description — New Module 30: Autonomous IR Assistant Layer"),
        p("Refer: FIG 28, FIG 29, FIG 30"),
        spacer(60),

        h2("9.1 Purpose"),
        p("Module 30 provides a fully autonomous background IR Assistant that silently monitors every internal and external meeting across any conferencing platform, proactively executes the full scope of Investor Relations, ESG, AGM, crisis communications, and NGO workflows, and delivers strategic support outputs — all with zero operator input after initial one-time calendar integration."),
        spacer(60),

        h2("9.2 System Architecture"),
        p("The Autonomous IR Assistant Layer comprises five interconnected subsystems:"),
        spacer(60),

        h3("9.2.1 Calendar Integration Engine"),
        p("The system integrates with the organisation's calendar infrastructure (Microsoft 365, Google Workspace, or equivalent) through a one-time OAuth authentication. Once connected, the engine continuously monitors all scheduled meetings across all employees in the organisation, regardless of platform."),
        bullet("Automatic event detection: every new calendar entry is classified by context (earnings call, board meeting, investor briefing, internal strategy, AGM, ESG review, donor meeting, crisis response, media briefing)"),
        bullet("Platform detection: the system identifies the conferencing platform (Zoom, Teams, Meet, Webex, telephony bridge, or other) and prepares the appropriate silent capture method"),
        bullet("Pre-meeting trigger: the system activates proactive workflows 24 hours before each detected meeting"),
        spacer(60),

        h3("9.2.2 Proactive Pre-Meeting Workflow Engine"),
        p("For each detected meeting, the system autonomously executes context-appropriate preparation workflows:"),
        bulletBold("Earnings Calls: ", "Generates AI-powered preparation brief including predicted analyst questions (based on historical patterns from Module 10), peer company sentiment comparison, compliance risk areas, and suggested talking points"),
        bulletBold("Board Meetings: ", "Prepares board-ready intelligence summary, outstanding action items from prior meetings, regulatory updates relevant to agenda items, and ESG metric summaries"),
        bulletBold("Investor Briefings: ", "Generates investor profile analysis, recent sentiment history for attending investors, predicted concern areas, and communication strategy recommendations"),
        bulletBold("AGM Preparation: ", "Compiles shareholder resolution analysis, proxy voting trend data, likely protest topics, and media monitoring summary"),
        bulletBold("Crisis Response: ", "Activates crisis protocol with real-time media monitoring, stakeholder impact assessment, draft holding statements, and regulatory notification checklists"),
        bulletBold("NGO/Donor Meetings: ", "Generates donor impact scoring, programme effectiveness metrics, grant compliance status, and stakeholder engagement analysis"),
        spacer(60),

        h3("9.2.3 Silent Capture and Real-Time Analysis"),
        p("During each meeting, the system deploys a silent AI agent (using the cross-platform capture methods described in Module 5 of the parent specification) to:"),
        bullet("Capture full audio transcription with speaker attribution"),
        bullet("Perform real-time sentiment analysis per speaker"),
        bullet("Monitor for compliance-sensitive language across all applicable jurisdictions"),
        bullet("Detect crisis indicators and trigger immediate alerts if thresholds are breached"),
        bullet("Record the session for post-meeting analysis and audit purposes"),
        spacer(60),

        h3("9.2.4 Proactive Post-Meeting Workflow Engine"),
        p("Immediately after each meeting concludes, the system autonomously executes:"),
        bullet("AI-generated meeting intelligence report with full analysis across all 20 intelligence modules (Module 28)"),
        bullet("Draft follow-up communications (investor thank-you notes, media statements, regulatory notifications) appropriate to meeting type"),
        bullet("Action item extraction with assignee detection and deadline inference"),
        bullet("Clean Disclosure Certificate generation with blockchain integrity hash (Module 22)"),
        bullet("Compliance review flagging any statements requiring legal review before public release"),
        bullet("ESG impact scoring for any environmental, social, or governance topics discussed"),
        bullet("Valuation impact simulation predicting market reaction to disclosed information (Module 24)"),
        spacer(60),

        h3("9.2.5 Monthly Executive Intelligence Report"),
        p("The system automatically compiles a monthly executive intelligence report aggregating all meetings processed during the period:"),
        bullet("Communication Health Score trending across all events"),
        bullet("Sentiment trajectory analysis by stakeholder category"),
        bullet("Compliance incident summary with resolution status"),
        bullet("ESG disclosure gap analysis"),
        bullet("Investor engagement ROI metrics (Module 25)"),
        bullet("Crisis risk forecast for the upcoming period"),
        bullet("Recommended actions prioritised by business impact"),
        bullet("Clean Disclosure Certificate summary for the period"),
        p("This report is delivered as a formatted PDF with an accompanying private AI advisory bot that can answer questions about any meeting or metric covered in the report."),
        spacer(60),

        h2("9.3 Novel Elements"),
        bullet("First system to provide fully autonomous proactive execution of IR, ESG, AGM, crisis, and NGO workflows from silent background monitoring — no human initiation required at any stage"),
        bullet("First platform that combines calendar-driven automatic meeting detection with context-classified pre-meeting preparation, silent capture, post-meeting workflow execution, and monthly aggregated reporting in a single closed-loop system"),
        bullet("First system to deliver a private AI advisory bot as part of a monthly intelligence report, providing interactive analysis of all captured communications"),
        spacer(),

        pageBreak(),

        // ──────────────── 10. MODULE 31 DETAILED ────────────────
        h1("10. Detailed Description — New Module 31: Autonomous Self-Expansion Engine for AGI Transition"),
        p("Refer: FIG 31, FIG 32, FIG 33, FIG 34"),
        spacer(60),

        h2("10.1 Purpose"),
        p("Module 31 provides an autonomous self-expansion engine that continuously observes its own performance across all corporate and non-profit communications (listed companies, NGOs, regulators, asset managers), identifies new capability gaps, proposes entirely new AI tools, tests them in shadow mode, and seamlessly integrates them into the platform — without any human input — to ensure the system evolves toward advanced autonomous intelligence as the technology matures."),
        spacer(60),

        h2("10.2 Relationship to Module 28"),
        p("Module 28 (Autonomous AI Self-Evolution Engine, CIP Submission 3) established the foundation for autonomous self-improvement through six algorithms: Module Quality Scoring, Evidence Decay, Cross-Event Correlation, Autonomous Promotion Pipeline, Gap Detection Matrix, and Impact Estimation. Module 28 identifies what needs improving. Module 31 extends this by autonomously building and deploying the improvements — closing the final gap between identifying a capability need and fulfilling it."),
        spacer(60),

        h2("10.3 System Architecture"),

        h3("10.3.1 Capability Gap Identification"),
        p("The engine continuously monitors every output from Modules 1–30 using:"),
        bullet("Algorithmic quality scoring from Module 28's six algorithms"),
        bullet("Cross-event correlation identifying systematic platform limitations"),
        bullet("User engagement analysis detecting which intelligence outputs are most/least accessed"),
        bullet("Regulatory horizon scanning identifying upcoming compliance requirements not yet covered"),
        bullet("Competitive intelligence monitoring detecting capabilities offered by emerging competitors"),
        spacer(60),

        h3("10.3.2 Autonomous Tool Proposal Generation"),
        p("When systematic gaps are detected, the engine autonomously generates tool proposals:"),
        bullet("Each proposal includes: capability description, expected inputs, expected outputs, integration points with existing modules, estimated complexity, and predicted impact score"),
        bullet("Proposals are generated using a large language model (LLM) with full context of the existing module architecture, available data sources, and regulatory requirements"),
        bullet("Multiple proposals may be generated for the same gap, representing alternative implementation approaches"),
        spacer(60),

        h3("10.3.3 Shadow Mode Testing"),
        p("Each proposed tool is tested in shadow mode before any production deployment:"),
        bullet("The tool is built automatically using code generation capabilities"),
        bullet("Historical data from the platform's event archive is used as test input"),
        bullet("The tool processes historical events and its outputs are compared against known outcomes and expert baselines"),
        bullet("Quality metrics (depth, breadth, specificity) are calculated using Module 28's scoring algorithms"),
        bullet("A minimum validation threshold must be met across at least 10 historical events before the tool can proceed"),
        bullet("Shadow testing runs in an isolated environment that cannot affect production outputs"),
        spacer(60),

        h3("10.3.4 Autonomous Integration"),
        p("Tools that pass shadow mode validation are automatically integrated:"),
        bullet("The tool is deployed to the production platform as a new intelligence module"),
        bullet("It is activated for all clients automatically (with per-client opt-out capability)"),
        bullet("Its outputs are included in the standard intelligence report pipeline"),
        bullet("Module 28's quality scoring begins monitoring the new tool immediately"),
        bullet("If quality degrades below acceptable thresholds post-deployment, the tool is automatically deactivated"),
        spacer(60),

        h3("10.3.5 Capability Roadmap"),
        p("The engine maintains a predictive capability roadmap:"),
        bullet("Based on observed gap trajectories, the system predicts which new capabilities will be needed in the next 30, 60, and 90 days"),
        bullet("Architecture preparations (data schema extensions, API endpoints, UI placeholders) are made in advance"),
        bullet("The roadmap is continuously updated as new events are processed and new gaps are identified"),
        spacer(60),

        h3("11.3.6 Blockchain-Certified Evolution History"),
        p("All expansion activities are logged with blockchain certification (using Module 22's integrity chain):"),
        bullet("Every tool proposal, test result, deployment decision, and deactivation is recorded with an immutable hash"),
        bullet("The complete evolution history of the platform is auditable by regulators, clients, and internal governance"),
        bullet("No expansion can be retroactively hidden or modified"),
        spacer(60),

        h2("10.4 Novel Elements"),
        bullet("First system to provide fully autonomous self-expansion of new AI capabilities across the entire spectrum of corporate and non-profit communications without human intervention"),
        bullet("First platform that combines universal silent capture, proactive IR assistance, and self-expansion mechanisms designed to evolve toward advanced autonomous intelligence"),
        bullet("First system to implement shadow-mode testing of autonomously generated AI tools using historical event data as validation"),
        bullet("First platform to maintain a blockchain-certified audit trail of its own autonomous evolution"),
        bullet("The closed-loop self-expansion engine creates a compounding intelligence advantage — each capability added enables detection of the next capability gap, creating accelerating improvement"),
        spacer(),

        pageBreak(),

        // ──────────────── 11. EMBODIMENTS ────────────────
        h1("11. Embodiments"),
        spacer(60),

        h2("11.1 Listed Company Embodiment"),
        p("For publicly listed companies, the system operates as a comprehensive IR intelligence platform:"),
        bullet("Full IR workflow automation including earnings call preparation, post-event drafting, and SENS/RNS notification preparation"),
        bullet("Valuation impact analysis simulating the effect of each communication on fair value and share price (Module 24)"),
        bullet("Multi-jurisdiction compliance orchestration across JSE, SEC, FCA, EU MAR, and other applicable frameworks (Module 20)"),
        bullet("Monthly executive intelligence reports with Clean Disclosure Certificates"),
        bullet("Private AI advisory bot for the C-suite and IR team"),
        spacer(60),

        h2("11.2 NGO / Non-Profit Embodiment"),
        p("For non-governmental organisations and non-profits, the system adapts its workflows:"),
        bullet("Stakeholder impact scoring replacing investor sentiment analysis"),
        bullet("Donor engagement analysis replacing investor engagement ROI"),
        bullet("Programme effectiveness metrics derived from internal meeting analysis"),
        bullet("Grant compliance monitoring adapted from securities compliance modules"),
        bullet("Board governance reporting tailored to NGO accountability frameworks"),
        spacer(60),

        h2("11.3 Multi-Jurisdiction Embodiment"),
        p("For organisations operating across multiple regulatory jurisdictions:"),
        bullet("Automatic detection of applicable regulations based on listing venue, investor domicile, and meeting context"),
        bullet("Parallel compliance checking against JSE Listings Requirements, SEC Regulation FD, FCA Disclosure Rules, EU Market Abuse Regulation, and other frameworks"),
        bullet("Jurisdiction-specific output formatting (SENS announcements for JSE, 8-K filings for SEC, RNS for London Stock Exchange)"),
        bullet("Conflict-of-law detection when communications may trigger obligations in multiple jurisdictions simultaneously"),
        spacer(60),

        h2("11.4 Crisis Embodiment"),
        p("For crisis communication scenarios:"),
        bullet("Real-time prediction of emerging crises based on communication signal deterioration patterns"),
        bullet("Automated crisis classification (financial, operational, reputational, regulatory, environmental)"),
        bullet("Instant generation of draft holding statements, stakeholder notification lists, and regulatory filings"),
        bullet("Media monitoring integration providing real-time external reaction analysis"),
        bullet("Post-crisis communication effectiveness scoring and lessons-learned generation"),
        spacer(),

        // ──────────────── 12. INDUSTRIAL APPLICABILITY ────────────────
        h1("12. Industrial Applicability"),
        p("The invention is directly applicable to the following industries and use cases:"),
        bullet("Listed companies (any exchange worldwide) — for comprehensive IR automation and compliance"),
        bullet("Investment banks and asset managers — for meeting intelligence and investor engagement analysis"),
        bullet("Securities exchanges and regulators — for market surveillance and disclosure monitoring"),
        bullet("Non-governmental organisations — for stakeholder engagement and donor relationship intelligence"),
        bullet("Corporate communications agencies — for multi-client intelligence management"),
        bullet("Law firms specialising in securities law — for compliance monitoring and disclosure review"),
        p("The system reduces manual IR and communications workload by an estimated 80%+ while providing audit-proof compliance documentation and strategic communication intelligence that is not achievable through manual processes."),
        spacer(),

        // ──────────────── 13. ALTERNATIVE IMPLEMENTATIONS ────────────────
        h1("13. Alternative Implementations"),
        p("The systems and methods described in this specification may be implemented using a variety of computational architectures and analytical techniques."),
        p("The AI analysis engines may operate using machine learning models, neural networks, natural language processing systems, large language models (including but not limited to GPT-4o, Claude, Gemini, Llama, or domain-specific fine-tuned models), rule-based systems, statistical models, hybrid analytical systems, or equivalent computational mechanisms."),
        p("Communication signals may be captured from any communication platform including telephony systems, web conferencing platforms, video conferencing platforms, webcast platforms, messaging platforms, or other communication infrastructures."),
        p("The blockchain certification may utilise any distributed ledger technology, hash chain, Merkle tree, or equivalent tamper-evident data structure."),
        p("The self-expansion engine may utilise any code generation method including LLM-based code generation, template-based generation, or hybrid approaches."),
        p("The specific examples, thresholds, and implementation details described in this specification are provided for illustrative purposes and should not be interpreted as limiting the scope of the invention to any particular technology, model, parameter value, or implementation approach."),
        spacer(),

        pageBreak(),

        // ──────────────── 14. CLAIMS ────────────────
        h1("14. Claims"),
        p("The following claims supplement Claims 1–43 of the prior filings incorporated by reference."),
        spacer(60),

        pBold("Independent System Claims:"),
        spacer(40),

        pBold("Claim 44 (Independent):"),
        p("A computer-implemented system for autonomous investor communication intelligence, comprising: (a) a silent capture engine configured to autonomously connect to and monitor communication events across any conferencing platform without end-user configuration; (b) an autonomous IR assistant layer configured to proactively execute investor relations, ESG, AGM, crisis communication, and NGO workflows before, during, and after each captured event without human initiation; (c) a monthly executive intelligence report generator that automatically aggregates intelligence from all captured events; and (d) a private AI advisory bot that provides interactive analysis of all captured communications."),
        spacer(60),

        pBold("Claim 45 (Dependent on 44):"),
        p("The system of claim 44, wherein the autonomous IR assistant layer further comprises: (a) a calendar integration engine that monitors all scheduled meetings across the organisation and classifies each by context type including earnings call, board meeting, investor briefing, AGM, crisis response, and donor meeting; (b) a proactive pre-meeting workflow engine that generates context-appropriate preparation materials at least 24 hours before each meeting; and (c) a proactive post-meeting workflow engine that generates intelligence reports, draft follow-up communications, action items, and compliance reviews immediately after each meeting concludes."),
        spacer(60),

        pBold("Claim 46 (Dependent on 44):"),
        p("The system of claim 44, further comprising a Clean Disclosure Certificate generator that produces blockchain-certified attestation of the completeness and compliance status of communications processed during each event, using immutable hash chains to provide audit-proof integrity verification."),
        spacer(60),

        pBold("Claim 47 (Dependent on 44):"),
        p("The system of claim 44, further comprising a multi-jurisdiction compliance orchestration engine that automatically detects applicable regulatory frameworks based on listing venue and investor domicile, and performs parallel compliance checking against at least JSE Listings Requirements, SEC Regulation FD, FCA Disclosure Rules, and EU Market Abuse Regulation."),
        spacer(60),

        pBold("Claim 48 (Dependent on 44):"),
        p("The system of claim 44, further comprising a real-time crisis prediction engine that monitors communication signals during events and generates automated crisis alerts, classification, draft holding statements, and regulatory notification checklists when crisis indicator thresholds are breached."),
        spacer(60),

        pBold("Claim 49 (Dependent on 44):"),
        p("The system of claim 44, further comprising a valuation impact simulation engine that models the predicted effect of disclosed information on company fair value, share price, and investor sentiment, and generates fair-value-gap alerts when communication content is predicted to cause material market reaction."),
        spacer(60),

        pBold("Independent Method Claim:"),
        spacer(40),

        pBold("Claim 50 (Independent):"),
        p("A computer-implemented method for autonomous self-expansion of an AI communication intelligence platform toward advanced autonomous intelligence, comprising the steps of: (a) continuously monitoring outputs from all intelligence modules across corporate and non-profit communications; (b) algorithmically identifying new capability gaps using quality scoring and cross-event correlation; (c) autonomously generating tool proposals including capability description, expected inputs and outputs, integration points, and predicted impact scores; (d) testing each proposed tool in shadow mode against historical event data using an isolated environment; (e) validating tool quality using algorithmic scoring across depth, breadth, and specificity dimensions against a minimum threshold; (f) automatically deploying validated tools to the production platform; (g) continuously monitoring deployed tools and automatically deactivating any whose quality degrades below acceptable thresholds; and (h) repeating steps (a) through (g) for each subsequent intelligence report, creating an accelerating self-improvement cycle."),
        spacer(60),

        pBold("Claim 51 (Dependent on 50):"),
        p("The method of claim 50, further comprising maintaining a predictive capability roadmap that forecasts new capabilities needed in future periods based on observed gap trajectories, and preparing architecture extensions in advance of predicted capability needs."),
        spacer(60),

        pBold("Claim 52 (Dependent on 50):"),
        p("The method of claim 50, further comprising recording every tool proposal, shadow test result, deployment decision, and deactivation in a blockchain-certified evolution history, providing an immutable audit trail of the platform's autonomous evolution."),
        spacer(60),

        pBold("Claim 53 (Dependent on 50):"),
        p("The method of claim 50, wherein the shadow mode testing step comprises: (a) automatically generating tool implementation code using large language model code generation; (b) processing at least 10 historical events through the proposed tool in an isolated environment; (c) comparing tool outputs against known outcomes and expert baselines; and (d) calculating quality metrics across depth, breadth, and specificity dimensions, wherein only tools meeting a minimum composite quality score proceed to production deployment."),
        spacer(60),

        pBold("Claim 54 (Dependent on 44):"),
        p("The system of claim 44, adapted for non-governmental organisations, wherein investor sentiment analysis is replaced by stakeholder impact scoring, investor engagement ROI is replaced by donor engagement analysis, and securities compliance monitoring is replaced by grant compliance monitoring."),
        spacer(60),

        pBold("Claim 55 (Dependent on 44):"),
        p("The system of claim 44, further comprising a private AI advisory bot delivered as part of each monthly intelligence report, wherein the bot has access to all communications captured during the reporting period and provides interactive natural-language analysis to authorised users."),
        spacer(60),

        h2("Complete Claims Summary"),
        new Table({
          rows: [
            new TableRow({ children: [hCell("Claims", 1500), hCell("Type", 2000), hCell("Scope", 4000), hCell("Filing", 2500)] }),
            new TableRow({ children: [tCell("1–15", 1500), tCell("System", 2000), tCell("Core platform: monitoring, AI analysis, cross-platform capture, OCC, benchmarking, compliance, self-improving models", 4000), tCell("Parent Provisional", 2500)] }),
            new TableRow({ children: [tCell("16–20", 1500), tCell("Method", 2000), tCell("Cross-platform capture, benchmarking, collaborative management, self-improving models", 4000), tCell("Parent Provisional", 2500)] }),
            new TableRow({ children: [tCell("21–25", 1500), tCell("Autonomous", 2000), tCell("Self-evolving platform, pattern discovery, predictive briefings, benchmark evolution", 4000), tCell("Parent Provisional", 2500)] }),
            new TableRow({ children: [tCell("26–33", 1500), tCell("CIP System", 2000), tCell("Autonomous Modules 19–27", 4000), tCell("CIP Submission 2", 2500)] }),
            new TableRow({ children: [tCell("34–43", 1500), tCell("CIP System/Method", 2000), tCell("Module 28: Self-Evolution Engine (6 algorithms)", 4000), tCell("CIP Submission 3", 2500)] }),
            new TableRow({ children: [tCell("44–49", 1500), tCell("System", 2000), tCell("Module 30: IR Assistant + compliance + crisis + valuation", 4000), tCell("CIP Submission 4", 2500)] }),
            new TableRow({ children: [tCell("50–53", 1500), tCell("Method", 2000), tCell("Module 31: Self-Expansion Engine + shadow testing + roadmap", 4000), tCell("CIP Submission 4", 2500)] }),
            new TableRow({ children: [tCell("54–55", 1500), tCell("System (Dependent)", 2000), tCell("NGO adaptation + Private AI Bot", 4000), tCell("CIP Submission 4", 2500)] }),
          ],
          width: { size: 10000, type: WidthType.DXA },
        }),
        pBold("Total: 55 independent and dependent claims across all filings."),
        spacer(),

        pageBreak(),

        // ──────────────── 15. DRAWINGS ────────────────
        h1("15. Drawings"),
        p("The following figures (FIG 28–34) supplement Figures 1–12 of the parent provisional, Figures 13–20 of CIP Submission 2, and Figures 21–27 of CIP Submission 3."),
        spacer(),

        // ──── FIG 28 ────
        h2("FIG 28 — Autonomous IR Assistant Layer: Complete System Architecture"),
        ...diagram([
          "╔══════════════════════════════════════════════════════════════════╗",
          "║              AUTONOMOUS IR ASSISTANT LAYER (Module 30)         ║",
          "╠══════════════════════════════════════════════════════════════════╣",
          "║                                                                ║",
          "║  ┌──────────────────────────┐                                  ║",
          "║  │   CALENDAR INTEGRATION   │ (Microsoft 365 / Google / Other) ║",
          "║  │   • Auto-detect meetings │                                  ║",
          "║  │   • Classify context      │                                 ║",
          "║  │   • Identify platform     │                                 ║",
          "║  └────────────┬─────────────┘                                  ║",
          "║               │                                                ║",
          "║       ┌───────┴───────┐                                        ║",
          "║       │               │                                        ║",
          "║       ▼               ▼                                        ║",
          "║  ┌──────────┐  ┌──────────┐     ┌──────────────────────────┐   ║",
          "║  │PRE-MEET  │  │ SILENT   │────▶│ REAL-TIME ANALYSIS       │   ║",
          "║  │WORKFLOW  │  │ CAPTURE  │     │ • Transcription          │   ║",
          "║  │• Brief   │  │ ENGINE   │     │ • Sentiment per speaker  │   ║",
          "║  │• Q&A prep│  │(Module 5)│     │ • Compliance flags       │   ║",
          "║  │• Risk    │  └──────────┘     │ • Crisis indicators      │   ║",
          "║  └──────────┘                   └────────────┬─────────────┘   ║",
          "║                                              │                 ║",
          "║                                              ▼                 ║",
          "║                                ┌──────────────────────────┐    ║",
          "║                                │ POST-MEETING WORKFLOW    │    ║",
          "║                                │ • AI Intelligence Report │    ║",
          "║                                │ • Draft Communications   │    ║",
          "║                                │ • Action Items           │    ║",
          "║                                │ • Clean Disclosure Cert  │    ║",
          "║                                │ • ESG Impact Score       │    ║",
          "║                                │ • Valuation Impact Sim   │    ║",
          "║                                └────────────┬─────────────┘   ║",
          "║                                              │                 ║",
          "║                                              ▼                 ║",
          "║                                ┌──────────────────────────┐    ║",
          "║                                │ MONTHLY EXECUTIVE REPORT │    ║",
          "║                                │ + Private AI Advisory Bot│    ║",
          "║                                │ + Clean Disclosure Certs │    ║",
          "║                                └──────────────────────────┘    ║",
          "║                                                                ║",
          "╚══════════════════════════════════════════════════════════════════╝",
        ], "FIG 28 — Complete architecture of the Autonomous IR Assistant Layer showing the end-to-end flow from calendar integration through pre-meeting preparation, silent capture, real-time analysis, post-meeting workflows, and monthly reporting."),

        pageBreak(),

        // ──── FIG 29 ────
        h2("FIG 29 — Pre-Meeting Workflow Engine: Context-Classified Preparation"),
        ...diagram([
          "╔══════════════════════════════════════════════════════════════════╗",
          "║          PRE-MEETING WORKFLOW ENGINE                           ║",
          "╠══════════════════════════════════════════════════════════════════╣",
          "║                                                                ║",
          "║  ┌───────────────────────────────────────┐                     ║",
          "║  │  DETECTED MEETING (from Calendar)     │                     ║",
          "║  │  Context: [auto-classified]            │                     ║",
          "║  └───────────────────┬───────────────────┘                     ║",
          "║                      │                                         ║",
          "║     ┌────────┬───────┼────────┬─────────┬──────────┐          ║",
          "║     ▼        ▼       ▼        ▼         ▼          ▼          ║",
          "║  ┌───────┐┌───────┐┌───────┐┌───────┐┌────────┐┌────────┐    ║",
          "║  │EARNING││BOARD  ││INVEST-││  AGM  ││CRISIS  ││  NGO/  │    ║",
          "║  │ CALL  ││MEETING││OR     ││       ││RESPONSE││ DONOR  │    ║",
          "║  ├───────┤├───────┤├───────┤├───────┤├────────┤├────────┤    ║",
          "║  │Predict││Board- ││Invest-││Share- ││Media   ││Donor   │    ║",
          "║  │analyst││ready  ││or     ││holder ││monitor-││impact  │    ║",
          "║  │Q&A    ││summary││profile││resolu-││ing     ││scoring │    ║",
          "║  │       ││       ││       ││tion   ││       ││        │    ║",
          "║  │Peer   ││Action ││Senti- ││analysis││Draft  ││Grant   │    ║",
          "║  │compare││items  ││ment   ││       ││holding││compli- │    ║",
          "║  │       ││       ││history││Proxy  ││state- ││ance    │    ║",
          "║  │Compli-││Regul- ││       ││voting ││ments  ││        │    ║",
          "║  │ance   ││atory  ││Concern││trends ││       ││Stake-  │    ║",
          "║  │risks  ││updates││areas  ││       ││Regul- ││holder  │    ║",
          "║  │       ││       ││       ││Media  ││atory  ││engage- │    ║",
          "║  │Talking││ESG    ││Strat- ││monitor││notify ││ment    │    ║",
          "║  │points ││metrics││egy    ││       ││       ││        │    ║",
          "║  └───────┘└───────┘└───────┘└───────┘└────────┘└────────┘    ║",
          "║                                                                ║",
          "║  Output: Context-appropriate preparation brief                 ║",
          "║  Timing: Delivered 24 hours before meeting                     ║",
          "║  Input:  Zero — fully autonomous                               ║",
          "║                                                                ║",
          "╚══════════════════════════════════════════════════════════════════╝",
        ], "FIG 29 — Pre-meeting workflow engine showing context classification and the six distinct preparation workflow types."),

        pageBreak(),

        // ──── FIG 30 ────
        h2("FIG 30 — Monthly Executive Intelligence Report: Aggregation Pipeline"),
        ...diagram([
          "    ┌─────────────┐  ┌─────────────┐  ┌─────────────┐",
          "    │  Meeting 1  │  │  Meeting 2  │  │  Meeting N  │",
          "    │  (Week 1)   │  │  (Week 1)   │  │  (Week 4)   │",
          "    └──────┬──────┘  └──────┬──────┘  └──────┬──────┘",
          "           │               │               │         ",
          "           └───────────────┼───────────────┘         ",
          "                           │                          ",
          "                           ▼                          ",
          "           ┌───────────────────────────────┐          ",
          "           │  MONTHLY AGGREGATION ENGINE   │          ",
          "           │  • Compile all event reports  │          ",
          "           │  • Calculate period metrics   │          ",
          "           │  • Trend analysis             │          ",
          "           │  • Risk forecasting           │          ",
          "           └───────────────┬───────────────┘          ",
          "                           │                          ",
          "           ┌───────────────┼───────────────┐          ",
          "           │               │               │          ",
          "           ▼               ▼               ▼          ",
          "  ┌─────────────┐ ┌─────────────┐ ┌──────────────┐   ",
          "  │  EXECUTIVE  │ │  PRIVATE AI │ │    CLEAN     │   ",
          "  │   REPORT    │ │  ADVISORY   │ │ DISCLOSURE   │   ",
          "  │  (PDF)      │ │    BOT      │ │ CERTIFICATES │   ",
          "  │             │ │             │ │  (Blockchain) │   ",
          "  │ • Health    │ │ • Q&A on    │ │              │   ",
          "  │   Score     │ │   any event │ │ • Immutable  │   ",
          "  │ • Sentiment │ │ • Metric    │ │   hash chain │   ",
          "  │ • Compliance│ │   drill-    │ │ • Per-event  │   ",
          "  │ • ESG Gaps  │ │   down      │ │   attestation│   ",
          "  │ • ROI       │ │ • Strategy  │ │              │   ",
          "  │ • Crisis    │ │   advice    │ │              │   ",
          "  │   Forecast  │ │             │ │              │   ",
          "  │ • Actions   │ │             │ │              │   ",
          "  └─────────────┘ └─────────────┘ └──────────────┘   ",
        ], "FIG 30 — Monthly report aggregation pipeline showing the three deliverables: Executive Report, Private AI Bot, and Clean Disclosure Certificates."),

        pageBreak(),

        // ──── FIG 31 ────
        h2("FIG 31 — Self-Expansion Engine: Complete System Architecture"),
        ...diagram([
          "╔══════════════════════════════════════════════════════════════════╗",
          "║      AUTONOMOUS SELF-EXPANSION ENGINE (Module 31)              ║",
          "╠══════════════════════════════════════════════════════════════════╣",
          "║                                                                ║",
          "║  ┌──────────────────────────────────────────────┐              ║",
          "║  │ CONTINUOUS MONITORING                        │              ║",
          "║  │ • Module 28 quality scores (all outputs)    │              ║",
          "║  │ • Cross-event correlation patterns           │              ║",
          "║  │ • User engagement analytics                  │              ║",
          "║  │ • Regulatory horizon scanning                │              ║",
          "║  │ • Competitive intelligence                   │              ║",
          "║  └────────────────────┬─────────────────────────┘              ║",
          "║                       │                                        ║",
          "║              [Gap detected]                                    ║",
          "║                       │                                        ║",
          "║                       ▼                                        ║",
          "║  ┌──────────────────────────────────────────────┐              ║",
          "║  │ TOOL PROPOSAL GENERATION (LLM)              │              ║",
          "║  │ • Capability description                     │              ║",
          "║  │ • Expected inputs / outputs                  │              ║",
          "║  │ • Integration points with Modules 1–30      │              ║",
          "║  │ • Predicted impact score                     │              ║",
          "║  └────────────────────┬─────────────────────────┘              ║",
          "║                       │                                        ║",
          "║                       ▼                                        ║",
          "║  ┌──────────────────────────────────────────────┐              ║",
          "║  │ SHADOW MODE TESTING (Isolated Environment)  │              ║",
          "║  │ • Auto-generate tool code (LLM)             │              ║",
          "║  │ • Process 10+ historical events              │              ║",
          "║  │ • Compare against baselines                  │              ║",
          "║  │ • Score: depth / breadth / specificity       │              ║",
          "║  │ • Minimum quality threshold gate             │              ║",
          "║  └─────────┬───────────────────┬────────────────┘              ║",
          "║            │                   │                                ║",
          "║      [PASS]│             [FAIL]│                                ║",
          "║            ▼                   ▼                                ║",
          "║  ┌──────────────┐    ┌──────────────┐                          ║",
          "║  │ AUTO-DEPLOY  │    │  REJECT /    │                          ║",
          "║  │ TO PRODUCTION│    │  RE-PROPOSE  │                          ║",
          "║  │ + activate   │    └──────────────┘                          ║",
          "║  │   for all    │                                              ║",
          "║  │   clients    │                                              ║",
          "║  └───────┬──────┘                                              ║",
          "║          │                                                     ║",
          "║          ▼                                                     ║",
          "║  ┌──────────────────────────────────────────────┐              ║",
          "║  │ CONTINUOUS QUALITY MONITORING                │              ║",
          "║  │ • Module 28 scores new tool outputs          │              ║",
          "║  │ • Auto-deactivate if quality degrades        │              ║",
          "║  │ • Blockchain-log all decisions               │              ║",
          "║  └──────────────────────────────────────────────┘              ║",
          "║                                                                ║",
          "╚══════════════════════════════════════════════════════════════════╝",
        ], "FIG 31 — Complete architecture of the Self-Expansion Engine showing the autonomous cycle from gap detection through proposal, testing, deployment, and continuous monitoring."),

        pageBreak(),

        // ──── FIG 32 ────
        h2("FIG 32 — Shadow Mode Testing Pipeline"),
        ...diagram([
          "           ┌───────────────────────┐                  ",
          "           │   TOOL PROPOSAL       │                  ",
          "           │   (from LLM)          │                  ",
          "           └───────────┬───────────┘                  ",
          "                       │                              ",
          "              (1) Code Generation                     ",
          "                       │                              ",
          "                       ▼                              ",
          "           ┌───────────────────────┐                  ",
          "           │  AUTO-GENERATED CODE  │                  ",
          "           │  (LLM code gen)       │                  ",
          "           └───────────┬───────────┘                  ",
          "                       │                              ",
          "          (2) Load Historical Data                    ",
          "                       │                              ",
          "                       ▼                              ",
          "    ┌────────┐  ┌────────┐  ┌────────┐  ┌────────┐   ",
          "    │Event 1 │  │Event 2 │  │Event 3 │  │Event N │   ",
          "    │(hist.) │  │(hist.) │  │(hist.) │  │(≥ 10)  │   ",
          "    └───┬────┘  └───┬────┘  └───┬────┘  └───┬────┘   ",
          "        │           │           │           │         ",
          "        └─────────┬─┴───────────┴───────────┘         ",
          "                  │                                   ",
          "         (3) Process in Isolation                     ",
          "                  │                                   ",
          "                  ▼                                   ",
          "    ┌──────────────────────────────────┐              ",
          "    │ QUALITY SCORING (Module 28)      │              ",
          "    │ • Depth     (weight: 0.40)       │              ",
          "    │ • Breadth   (weight: 0.30)       │              ",
          "    │ • Specificity (weight: 0.30)     │              ",
          "    │                                  │              ",
          "    │ Compare vs. expert baselines     │              ",
          "    └──────────────┬───────────────────┘              ",
          "                   │                                  ",
          "          ┌────────┴────────┐                         ",
          "          │                 │                         ",
          "    [Score ≥ threshold]  [Score < threshold]          ",
          "          │                 │                         ",
          "          ▼                 ▼                         ",
          "   ┌────────────┐    ┌────────────┐                  ",
          "   │  APPROVED  │    │  REJECTED  │                  ",
          "   │  Deploy to │    │  Log reason │                  ",
          "   │  production│    │  May re-    │                  ",
          "   └────────────┘    │  propose    │                  ",
          "                     └────────────┘                  ",
        ], "FIG 32 — Shadow mode testing pipeline showing the four-stage validation process: code generation, historical data loading, isolated execution, and quality scoring."),

        pageBreak(),

        // ──── FIG 33 ────
        h2("FIG 33 — Capability Roadmap: Predictive Planning"),
        ...diagram([
          "╔══════════════════════════════════════════════════════════════╗",
          "║              PREDICTIVE CAPABILITY ROADMAP                  ║",
          "╠══════════════════════════════════════════════════════════════╣",
          "║                                                             ║",
          "║  CURRENT (Live)           30-DAY HORIZON                    ║",
          "║  ┌─────────────┐          ┌────────────────────────┐        ║",
          "║  │ 31 Active   │ ──gap──▶ │ Predicted Needs:       │        ║",
          "║  │ Modules     │ trends   │ • Peer comparison      │        ║",
          "║  │             │          │ • Forward guidance      │        ║",
          "║  │ Quality     │          │   parsing               │        ║",
          "║  │ scores from │          │                         │        ║",
          "║  │ Module 28   │          │ Confidence: HIGH        │        ║",
          "║  └─────────────┘          └────────────────────────┘        ║",
          "║                                                             ║",
          "║  60-DAY HORIZON           90-DAY HORIZON                    ║",
          "║  ┌────────────────────┐   ┌────────────────────────┐        ║",
          "║  │ Predicted Needs:   │   │ Predicted Needs:       │        ║",
          "║  │ • Multi-language   │   │ • Video sentiment      │        ║",
          "║  │   transcript       │   │   (facial analysis)    │        ║",
          "║  │ • Regulatory       │   │ • Cross-company        │        ║",
          "║  │   change tracker   │   │   correlation engine   │        ║",
          "║  │                    │   │                         │        ║",
          "║  │ Confidence: MEDIUM │   │ Confidence: EMERGING   │        ║",
          "║  └────────────────────┘   └────────────────────────┘        ║",
          "║                                                             ║",
          "║  ADVANCE PREPARATION:                                       ║",
          "║  ┌──────────────────────────────────────────────────┐       ║",
          "║  │ • Schema extensions designed for predicted tools │       ║",
          "║  │ • API endpoints reserved                         │       ║",
          "║  │ • Training data collection initiated             │       ║",
          "║  │ • Integration points identified in existing code │       ║",
          "║  └──────────────────────────────────────────────────┘       ║",
          "║                                                             ║",
          "╚══════════════════════════════════════════════════════════════╝",
        ], "FIG 33 — Predictive capability roadmap showing 30/60/90-day horizon planning with advance architecture preparation."),

        pageBreak(),

        // ──── FIG 34 ────
        h2("FIG 34 — Complete Platform: Closed-Loop Intelligence Cycle"),
        ...diagram([
          "                    ┌──────────────────┐                      ",
          "                    │  CALENDAR EVENT   │                      ",
          "                    │  DETECTED         │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    (1) Pre-meeting prep                       ",
          "                             │                                 ",
          "                             ▼                                 ",
          "                    ┌──────────────────┐                      ",
          "                    │  SILENT CAPTURE  │                      ",
          "                    │  (any platform)  │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    (2) Real-time analysis                     ",
          "                             │                                 ",
          "                             ▼                                 ",
          "                    ┌──────────────────┐                      ",
          "                    │  20-MODULE AI    │                      ",
          "                    │  REPORT          │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    (3) Post-meeting workflows                 ",
          "                             │                                 ",
          "                ┌────────────┼────────────┐                   ",
          "                │            │            │                   ",
          "                ▼            ▼            ▼                   ",
          "       ┌──────────┐ ┌──────────┐ ┌──────────────┐            ",
          "       │COMPLIANCE│ │VALUATION │ │BLOCKCHAIN    │            ",
          "       │CHECK     │ │IMPACT    │ │CERTIFICATION │            ",
          "       │(Mod 20)  │ │(Mod 24)  │ │(Module 22)   │            ",
          "       └──────────┘ └──────────┘ └──────────────┘            ",
          "                             │                                ",
          "                    (4) Quality scoring                        ",
          "                             │                                 ",
          "                             ▼                                 ",
          "                    ┌──────────────────┐                      ",
          "                    │  SELF-EVOLUTION  │                      ",
          "                    │  ENGINE (Mod 28) │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    (5) Gap detection                          ",
          "                             │                                 ",
          "                             ▼                                 ",
          "                    ┌──────────────────┐                      ",
          "                    │  SELF-EXPANSION  │                      ",
          "                    │  ENGINE (Mod 31) │                      ",
          "                    │  Shadow test +   │                      ",
          "                    │  auto-deploy     │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    (6) Monthly aggregation                    ",
          "                             │                                 ",
          "                             ▼                                 ",
          "                    ┌──────────────────┐                      ",
          "                    │  EXECUTIVE REPORT│                      ",
          "                    │  + AI BOT        │                      ",
          "                    │  + CERTIFICATES  │                      ",
          "                    └────────┬─────────┘                      ",
          "                             │                                 ",
          "                    ┌────────┘                                 ",
          "                    │   CLOSED LOOP — back to (1)             ",
          "                    └──────────────────────────▶               ",
        ], "FIG 34 — Complete platform closed-loop cycle showing the seven-stage intelligence pipeline from event detection through self-expansion and monthly reporting."),

        pageBreak(),

        // ──────────────── 16. INCORPORATION ────────────────
        h1("16. Incorporation by Reference"),
        p("The full specification, claims (1–43), drawings (FIG 1–FIG 27), definitions, detailed description, and all alternative implementations described in the following filings are incorporated by reference in their entirety:"),
        bullet("Parent provisional specification (Application ID 1773575338868, filed 12 March 2026): 13 modules, 25 claims, 12 figures"),
        bullet("CIP Submission 2 (filed 16 March 2026): 9 modules, 8 claims, 8 figures"),
        bullet("CIP Submission 3 (filed 18 March 2026): 1 module, 10 claims, 7 figures"),
        p("The new matter described in this filing supplements and extends the prior filings without modifying or replacing any of the parent claims or described embodiments."),
        spacer(),

        // ──────────────── 17. DECLARATION ────────────────
        h1("17. Declaration"),
        p("I, David Cameron, the applicant and inventor, declare that:"),
        bullet("The new matter described in this filing (Module 30 — Autonomous IR Assistant Layer, and Module 31 — Autonomous Self-Expansion Engine for AGI Transition) was not disclosed in the parent provisional patent specification (Application ID 1773575338868, filed 12 March 2026), CIP Submission 2 (filed 16 March 2026), or CIP Submission 3 (filed 18 March 2026)."),
        bullet("The new matter has been reduced to practice in a working implementation of the CuraLive platform, accessible at https://curalive-platform.replit.app."),
        bullet("The source code is maintained at github.com/davecameron187-sys/curalive-platform."),
        bullet("This filing is made within the priority period of the parent application."),
        spacer(200),

        new Paragraph({
          children: [new TextRun({ text: "_______________________________", font: FONT, size: S })],
        }),
        p("David Cameron"),
        p("Applicant and Inventor"),
        p("Date: 19 March 2026"),
        spacer(200),

        pItalic("This document is prepared for filing as a Continuation-in-Part (CIP) Submission with the Companies and Intellectual Property Commission (CIPC) of South Africa in accordance with the Patents Act 57 of 1978 and the Patent Regulations."),
        spacer(),

        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "— End of Specification —", bold: true, font: FONT, size: S })],
        }),
      ],
    },
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("attached_assets/CuraLive_CIPC_CIP_Submission_4_Complete.docx", buffer);
  console.log("CIPC CIP 4 DOCX generated successfully — " + (buffer.length / 1024).toFixed(0) + " KB");
});
