import { invokeLLM } from "../_core/llm";

export interface PredictiveRiskAssessment {
  overallRiskLevel: "low" | "moderate" | "elevated" | "high" | "critical";
  riskScore: number;
  predictedEscalations: PredictedEscalation[];
  autoGeneratedPolicies: CompliancePolicy[];
  jurisdictionAlerts: JurisdictionAlert[];
  reasoning: string;
}

export interface PredictedEscalation {
  trigger: string;
  probability: number;
  impact: "low" | "medium" | "high" | "critical";
  mitigationStrategy: string;
}

export interface CompliancePolicy {
  policyName: string;
  policyType: "disclosure" | "response_template" | "escalation_rule" | "safe_harbour" | "redaction";
  description: string;
  autoEnforce: boolean;
  ruleDefinition: string;
}

export interface JurisdictionAlert {
  jurisdiction: string;
  regulation: string;
  relevantSection: string;
  riskDescription: string;
  requiredAction: string;
}

export async function predictiveRiskAnalysis(
  sessionContext: {
    eventName: string;
    clientName: string;
    questions: Array<{
      text: string;
      category: string;
      complianceRiskScore: number;
      status: string;
    }>;
    existingFlags: Array<{
      jurisdiction: string;
      riskType: string;
      riskScore: number;
    }>;
  }
): Promise<PredictiveRiskAssessment> {
  try {
    const questionSummary = sessionContext.questions.slice(0, 20).map((q, i) =>
      `${i + 1}. [${q.category}] (risk: ${q.complianceRiskScore}) ${q.text.slice(0, 100)}`
    ).join("\n");

    const flagSummary = sessionContext.existingFlags.map(f =>
      `${f.jurisdiction}: ${f.riskType} (score: ${f.riskScore})`
    ).join(", ");

    const result = await invokeLLM({
      model: "openai:gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are CuraLive's AGI Corporate Compliance Layer. Perform predictive risk analysis on a live Q&A session and auto-generate compliance policies.

Jurisdictions: ZA_JSE (JSE Listings Requirements), US_SEC (Regulation FD), UK_FCA (MAR/DTR), EU_ESMA (MAR), Global best practices.

Return ONLY valid JSON:
{
  "overallRiskLevel": "low|moderate|elevated|high|critical",
  "riskScore": 0-100,
  "predictedEscalations": [
    {
      "trigger": "what could escalate",
      "probability": 0.0-1.0,
      "impact": "low|medium|high|critical",
      "mitigationStrategy": "how to prevent"
    }
  ],
  "autoGeneratedPolicies": [
    {
      "policyName": "short_name",
      "policyType": "disclosure|response_template|escalation_rule|safe_harbour|redaction",
      "description": "what this policy does",
      "autoEnforce": true/false,
      "ruleDefinition": "the actual rule logic"
    }
  ],
  "jurisdictionAlerts": [
    {
      "jurisdiction": "ZA_JSE|US_SEC|UK_FCA|EU_ESMA|global",
      "regulation": "specific regulation name",
      "relevantSection": "section reference",
      "riskDescription": "what the risk is",
      "requiredAction": "what must be done"
    }
  ],
  "reasoning": "analysis explanation"
}`
        },
        {
          role: "user",
          content: `Event: "${sessionContext.eventName}" | Client: "${sessionContext.clientName}"

Questions (${sessionContext.questions.length} total):
${questionSummary}

Existing Flags: ${flagSummary || "None"}`
        }
      ],
      temperature: 0.2,
    });

    const parsed = JSON.parse(result.text.replace(/```json?\n?/g, "").replace(/```/g, "").trim());
    return {
      overallRiskLevel: parsed.overallRiskLevel || "moderate",
      riskScore: Math.min(100, Math.max(0, parsed.riskScore || 30)),
      predictedEscalations: Array.isArray(parsed.predictedEscalations) ? parsed.predictedEscalations : [],
      autoGeneratedPolicies: Array.isArray(parsed.autoGeneratedPolicies) ? parsed.autoGeneratedPolicies : [],
      jurisdictionAlerts: Array.isArray(parsed.jurisdictionAlerts) ? parsed.jurisdictionAlerts : [],
      reasoning: parsed.reasoning || "",
    };
  } catch (err) {
    console.error("[AgiCompliance] Predictive risk analysis failed:", err);
    return {
      overallRiskLevel: "moderate",
      riskScore: 30,
      predictedEscalations: [],
      autoGeneratedPolicies: [],
      jurisdictionAlerts: [],
      reasoning: "Predictive analysis unavailable — manual review recommended",
    };
  }
}

export async function generateComplianceSafeResponse(
  questionText: string,
  category: string,
  jurisdictions: string[],
  existingDraft?: string
): Promise<{ safeResponse: string; modifications: string[]; disclaimers: string[] }> {
  try {
    const result = await invokeLLM({
      model: "openai:gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are the AGI Corporate Compliance Layer. Review a Q&A response and ensure it is fully compliant across all applicable jurisdictions.

Jurisdictions to check: ${jurisdictions.join(", ")}

Return JSON:
{
  "safeResponse": "the compliance-safe version",
  "modifications": ["list of changes made"],
  "disclaimers": ["required disclaimers to append"]
}`
        },
        {
          role: "user",
          content: `Category: ${category}\nQuestion: ${questionText}\n${existingDraft ? `Draft Response: ${existingDraft}` : "No existing draft — generate a safe response."}`
        }
      ],
      temperature: 0.2,
    });

    const parsed = JSON.parse(result.text.replace(/```json?\n?/g, "").replace(/```/g, "").trim());
    return {
      safeResponse: parsed.safeResponse || existingDraft || "",
      modifications: Array.isArray(parsed.modifications) ? parsed.modifications : [],
      disclaimers: Array.isArray(parsed.disclaimers) ? parsed.disclaimers : [],
    };
  } catch {
    return {
      safeResponse: existingDraft || "",
      modifications: [],
      disclaimers: ["Standard compliance disclaimer: This response has not been verified by the AGI compliance layer."],
    };
  }
}
